// Code generated by ent, DO NOT EDIT.

package bid

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the bid type in the database.
	Label = "bid"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPickupCoordinates holds the string denoting the pickup_coordinates field in the database.
	FieldPickupCoordinates = "pickup_coordinates"
	// FieldDeliveryCoordinates holds the string denoting the delivery_coordinates field in the database.
	FieldDeliveryCoordinates = "delivery_coordinates"
	// FieldVolumeM3 holds the string denoting the volume_m3 field in the database.
	FieldVolumeM3 = "volume_m3"
	// FieldWeightKg holds the string denoting the weight_kg field in the database.
	FieldWeightKg = "weight_kg"
	// FieldPickupTime holds the string denoting the pickup_time field in the database.
	FieldPickupTime = "pickup_time"
	// FieldMaxPrice holds the string denoting the max_price field in the database.
	FieldMaxPrice = "max_price"
	// FieldZoneID holds the string denoting the zone_id field in the database.
	FieldZoneID = "zone_id"
	// FieldItems holds the string denoting the items field in the database.
	FieldItems = "items"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the bid in the database.
	Table = "bids"
)

// Columns holds all SQL columns for bid fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldUserID,
	FieldPickupCoordinates,
	FieldDeliveryCoordinates,
	FieldVolumeM3,
	FieldWeightKg,
	FieldPickupTime,
	FieldMaxPrice,
	FieldZoneID,
	FieldItems,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "matching_service/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Bid queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPickupCoordinates orders the results by the pickup_coordinates field.
func ByPickupCoordinates(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPickupCoordinates, opts...).ToFunc()
}

// ByDeliveryCoordinates orders the results by the delivery_coordinates field.
func ByDeliveryCoordinates(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryCoordinates, opts...).ToFunc()
}

// ByVolumeM3 orders the results by the volume_m3 field.
func ByVolumeM3(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVolumeM3, opts...).ToFunc()
}

// ByWeightKg orders the results by the weight_kg field.
func ByWeightKg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeightKg, opts...).ToFunc()
}

// ByPickupTime orders the results by the pickup_time field.
func ByPickupTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPickupTime, opts...).ToFunc()
}

// ByMaxPrice orders the results by the max_price field.
func ByMaxPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxPrice, opts...).ToFunc()
}

// ByZoneID orders the results by the zone_id field.
func ByZoneID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZoneID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
