// Code generated by ent, DO NOT EDIT.

package ent

import (
	"auth_service/ent/predicate"
	"auth_service/ent/refreshtoken"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RefreshTokenUpdate is the builder for updating RefreshToken entities.
type RefreshTokenUpdate struct {
	config
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (_u *RefreshTokenUpdate) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *RefreshTokenUpdate) SetRevokedAt(v time.Time) *RefreshTokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *RefreshTokenUpdate) SetNillableRevokedAt(v *time.Time) *RefreshTokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *RefreshTokenUpdate) ClearRevokedAt() *RefreshTokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *RefreshTokenUpdate) SetUsedAt(v time.Time) *RefreshTokenUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *RefreshTokenUpdate) SetNillableUsedAt(v *time.Time) *RefreshTokenUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *RefreshTokenUpdate) ClearUsedAt() *RefreshTokenUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *RefreshTokenUpdate) SetUserAgent(v string) *RefreshTokenUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *RefreshTokenUpdate) SetNillableUserAgent(v *string) *RefreshTokenUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *RefreshTokenUpdate) ClearUserAgent() *RefreshTokenUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetIP sets the "ip" field.
func (_u *RefreshTokenUpdate) SetIP(v string) *RefreshTokenUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *RefreshTokenUpdate) SetNillableIP(v *string) *RefreshTokenUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *RefreshTokenUpdate) ClearIP() *RefreshTokenUpdate {
	_u.mutation.ClearIP()
	return _u
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (_u *RefreshTokenUpdate) Mutation() *RefreshTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RefreshTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefreshTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RefreshTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefreshTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RefreshTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(refreshtoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(refreshtoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(refreshtoken.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(refreshtoken.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(refreshtoken.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(refreshtoken.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(refreshtoken.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(refreshtoken.FieldIP, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RefreshTokenUpdateOne is the builder for updating a single RefreshToken entity.
type RefreshTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *RefreshTokenUpdateOne) SetRevokedAt(v time.Time) *RefreshTokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *RefreshTokenUpdateOne) SetNillableRevokedAt(v *time.Time) *RefreshTokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *RefreshTokenUpdateOne) ClearRevokedAt() *RefreshTokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *RefreshTokenUpdateOne) SetUsedAt(v time.Time) *RefreshTokenUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *RefreshTokenUpdateOne) SetNillableUsedAt(v *time.Time) *RefreshTokenUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *RefreshTokenUpdateOne) ClearUsedAt() *RefreshTokenUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *RefreshTokenUpdateOne) SetUserAgent(v string) *RefreshTokenUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *RefreshTokenUpdateOne) SetNillableUserAgent(v *string) *RefreshTokenUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *RefreshTokenUpdateOne) ClearUserAgent() *RefreshTokenUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetIP sets the "ip" field.
func (_u *RefreshTokenUpdateOne) SetIP(v string) *RefreshTokenUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *RefreshTokenUpdateOne) SetNillableIP(v *string) *RefreshTokenUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *RefreshTokenUpdateOne) ClearIP() *RefreshTokenUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (_u *RefreshTokenUpdateOne) Mutation() *RefreshTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (_u *RefreshTokenUpdateOne) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RefreshTokenUpdateOne) Select(field string, fields ...string) *RefreshTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RefreshToken entity.
func (_u *RefreshTokenUpdateOne) Save(ctx context.Context) (*RefreshToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefreshTokenUpdateOne) SaveX(ctx context.Context) *RefreshToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RefreshTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefreshTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RefreshTokenUpdateOne) sqlSave(ctx context.Context) (_node *RefreshToken, err error) {
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefreshToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refreshtoken.FieldID)
		for _, f := range fields {
			if !refreshtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refreshtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(refreshtoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(refreshtoken.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(refreshtoken.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(refreshtoken.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(refreshtoken.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(refreshtoken.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(refreshtoken.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(refreshtoken.FieldIP, field.TypeString)
	}
	_node = &RefreshToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
