// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"vehicle_service/ent/schema"
	"vehicle_service/ent/vehicle"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	vehicleFields := schema.Vehicle{}.Fields()
	_ = vehicleFields
	// vehicleDescCapacityWeightKg is the schema descriptor for capacity_weight_kg field.
	vehicleDescCapacityWeightKg := vehicleFields[6].Descriptor()
	// vehicle.DefaultCapacityWeightKg holds the default value on creation for the capacity_weight_kg field.
	vehicle.DefaultCapacityWeightKg = vehicleDescCapacityWeightKg.Default.(float64)
	// vehicleDescCapacityVolumeCbm is the schema descriptor for capacity_volume_cbm field.
	vehicleDescCapacityVolumeCbm := vehicleFields[7].Descriptor()
	// vehicle.DefaultCapacityVolumeCbm holds the default value on creation for the capacity_volume_cbm field.
	vehicle.DefaultCapacityVolumeCbm = vehicleDescCapacityVolumeCbm.Default.(float64)
	// vehicleDescCreatedAt is the schema descriptor for created_at field.
	vehicleDescCreatedAt := vehicleFields[9].Descriptor()
	// vehicle.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehicle.DefaultCreatedAt = vehicleDescCreatedAt.Default.(func() time.Time)
	// vehicleDescUpdatedAt is the schema descriptor for updated_at field.
	vehicleDescUpdatedAt := vehicleFields[10].Descriptor()
	// vehicle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehicle.DefaultUpdatedAt = vehicleDescUpdatedAt.Default.(func() time.Time)
	// vehicle.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehicle.UpdateDefaultUpdatedAt = vehicleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// vehicleDescID is the schema descriptor for id field.
	vehicleDescID := vehicleFields[0].Descriptor()
	// vehicle.DefaultID holds the default value on creation for the id field.
	vehicle.DefaultID = vehicleDescID.Default.(func() uuid.UUID)
}
