// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"user_service/ent/address"
	"user_service/ent/predicate"
	"user_service/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AddressUpdate) SetUserID(v uuid.UUID) *AddressUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableUserID(v *uuid.UUID) *AddressUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *AddressUpdate) SetLabel(v string) *AddressUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableLabel(v *string) *AddressUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *AddressUpdate) ClearLabel() *AddressUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *AddressUpdate) SetContactName(v string) *AddressUpdate {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableContactName(v *string) *AddressUpdate {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// ClearContactName clears the value of the "contact_name" field.
func (_u *AddressUpdate) ClearContactName() *AddressUpdate {
	_u.mutation.ClearContactName()
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *AddressUpdate) SetContactPhone(v string) *AddressUpdate {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableContactPhone(v *string) *AddressUpdate {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// ClearContactPhone clears the value of the "contact_phone" field.
func (_u *AddressUpdate) ClearContactPhone() *AddressUpdate {
	_u.mutation.ClearContactPhone()
	return _u
}

// SetLine1 sets the "line1" field.
func (_u *AddressUpdate) SetLine1(v string) *AddressUpdate {
	_u.mutation.SetLine1(v)
	return _u
}

// SetNillableLine1 sets the "line1" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableLine1(v *string) *AddressUpdate {
	if v != nil {
		_u.SetLine1(*v)
	}
	return _u
}

// SetWard sets the "ward" field.
func (_u *AddressUpdate) SetWard(v string) *AddressUpdate {
	_u.mutation.SetWard(v)
	return _u
}

// SetNillableWard sets the "ward" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableWard(v *string) *AddressUpdate {
	if v != nil {
		_u.SetWard(*v)
	}
	return _u
}

// ClearWard clears the value of the "ward" field.
func (_u *AddressUpdate) ClearWard() *AddressUpdate {
	_u.mutation.ClearWard()
	return _u
}

// SetDistrict sets the "district" field.
func (_u *AddressUpdate) SetDistrict(v string) *AddressUpdate {
	_u.mutation.SetDistrict(v)
	return _u
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableDistrict(v *string) *AddressUpdate {
	if v != nil {
		_u.SetDistrict(*v)
	}
	return _u
}

// ClearDistrict clears the value of the "district" field.
func (_u *AddressUpdate) ClearDistrict() *AddressUpdate {
	_u.mutation.ClearDistrict()
	return _u
}

// SetCity sets the "city" field.
func (_u *AddressUpdate) SetCity(v string) *AddressUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableCity(v *string) *AddressUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *AddressUpdate) ClearCity() *AddressUpdate {
	_u.mutation.ClearCity()
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *AddressUpdate) SetLatitude(v float64) *AddressUpdate {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableLatitude(v *float64) *AddressUpdate {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *AddressUpdate) AddLatitude(v float64) *AddressUpdate {
	_u.mutation.AddLatitude(v)
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *AddressUpdate) SetLongitude(v float64) *AddressUpdate {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableLongitude(v *float64) *AddressUpdate {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *AddressUpdate) AddLongitude(v float64) *AddressUpdate {
	_u.mutation.AddLongitude(v)
	return _u
}

// SetAddressType sets the "address_type" field.
func (_u *AddressUpdate) SetAddressType(v address.AddressType) *AddressUpdate {
	_u.mutation.SetAddressType(v)
	return _u
}

// SetNillableAddressType sets the "address_type" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableAddressType(v *address.AddressType) *AddressUpdate {
	if v != nil {
		_u.SetAddressType(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *AddressUpdate) SetIsDefault(v bool) *AddressUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableIsDefault(v *bool) *AddressUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddressUpdate) SetUpdatedAt(v time.Time) *AddressUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AddressUpdate) SetUser(v *User) *AddressUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdate) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AddressUpdate) ClearUser() *AddressUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AddressUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AddressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AddressUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := address.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdate) check() error {
	if v, ok := _u.mutation.AddressType(); ok {
		if err := address.AddressTypeValidator(v); err != nil {
			return &ValidationError{Name: "address_type", err: fmt.Errorf(`ent: validator failed for field "Address.address_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.user"`)
	}
	return nil
}

func (_u *AddressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(address.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(address.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(address.FieldContactName, field.TypeString, value)
	}
	if _u.mutation.ContactNameCleared() {
		_spec.ClearField(address.FieldContactName, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(address.FieldContactPhone, field.TypeString, value)
	}
	if _u.mutation.ContactPhoneCleared() {
		_spec.ClearField(address.FieldContactPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Line1(); ok {
		_spec.SetField(address.FieldLine1, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ward(); ok {
		_spec.SetField(address.FieldWard, field.TypeString, value)
	}
	if _u.mutation.WardCleared() {
		_spec.ClearField(address.FieldWard, field.TypeString)
	}
	if value, ok := _u.mutation.District(); ok {
		_spec.SetField(address.FieldDistrict, field.TypeString, value)
	}
	if _u.mutation.DistrictCleared() {
		_spec.ClearField(address.FieldDistrict, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(address.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(address.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(address.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddressType(); ok {
		_spec.SetField(address.FieldAddressType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(address.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(address.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UserTable,
			Columns: []string{address.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UserTable,
			Columns: []string{address.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetUserID sets the "user_id" field.
func (_u *AddressUpdateOne) SetUserID(v uuid.UUID) *AddressUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableUserID(v *uuid.UUID) *AddressUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *AddressUpdateOne) SetLabel(v string) *AddressUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableLabel(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *AddressUpdateOne) ClearLabel() *AddressUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *AddressUpdateOne) SetContactName(v string) *AddressUpdateOne {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableContactName(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// ClearContactName clears the value of the "contact_name" field.
func (_u *AddressUpdateOne) ClearContactName() *AddressUpdateOne {
	_u.mutation.ClearContactName()
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *AddressUpdateOne) SetContactPhone(v string) *AddressUpdateOne {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableContactPhone(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// ClearContactPhone clears the value of the "contact_phone" field.
func (_u *AddressUpdateOne) ClearContactPhone() *AddressUpdateOne {
	_u.mutation.ClearContactPhone()
	return _u
}

// SetLine1 sets the "line1" field.
func (_u *AddressUpdateOne) SetLine1(v string) *AddressUpdateOne {
	_u.mutation.SetLine1(v)
	return _u
}

// SetNillableLine1 sets the "line1" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableLine1(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetLine1(*v)
	}
	return _u
}

// SetWard sets the "ward" field.
func (_u *AddressUpdateOne) SetWard(v string) *AddressUpdateOne {
	_u.mutation.SetWard(v)
	return _u
}

// SetNillableWard sets the "ward" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableWard(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetWard(*v)
	}
	return _u
}

// ClearWard clears the value of the "ward" field.
func (_u *AddressUpdateOne) ClearWard() *AddressUpdateOne {
	_u.mutation.ClearWard()
	return _u
}

// SetDistrict sets the "district" field.
func (_u *AddressUpdateOne) SetDistrict(v string) *AddressUpdateOne {
	_u.mutation.SetDistrict(v)
	return _u
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableDistrict(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetDistrict(*v)
	}
	return _u
}

// ClearDistrict clears the value of the "district" field.
func (_u *AddressUpdateOne) ClearDistrict() *AddressUpdateOne {
	_u.mutation.ClearDistrict()
	return _u
}

// SetCity sets the "city" field.
func (_u *AddressUpdateOne) SetCity(v string) *AddressUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableCity(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *AddressUpdateOne) ClearCity() *AddressUpdateOne {
	_u.mutation.ClearCity()
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *AddressUpdateOne) SetLatitude(v float64) *AddressUpdateOne {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableLatitude(v *float64) *AddressUpdateOne {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *AddressUpdateOne) AddLatitude(v float64) *AddressUpdateOne {
	_u.mutation.AddLatitude(v)
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *AddressUpdateOne) SetLongitude(v float64) *AddressUpdateOne {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableLongitude(v *float64) *AddressUpdateOne {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *AddressUpdateOne) AddLongitude(v float64) *AddressUpdateOne {
	_u.mutation.AddLongitude(v)
	return _u
}

// SetAddressType sets the "address_type" field.
func (_u *AddressUpdateOne) SetAddressType(v address.AddressType) *AddressUpdateOne {
	_u.mutation.SetAddressType(v)
	return _u
}

// SetNillableAddressType sets the "address_type" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableAddressType(v *address.AddressType) *AddressUpdateOne {
	if v != nil {
		_u.SetAddressType(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *AddressUpdateOne) SetIsDefault(v bool) *AddressUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableIsDefault(v *bool) *AddressUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddressUpdateOne) SetUpdatedAt(v time.Time) *AddressUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AddressUpdateOne) SetUser(v *User) *AddressUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdateOne) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AddressUpdateOne) ClearUser() *AddressUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Address entity.
func (_u *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AddressUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := address.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdateOne) check() error {
	if v, ok := _u.mutation.AddressType(); ok {
		if err := address.AddressTypeValidator(v); err != nil {
			return &ValidationError{Name: "address_type", err: fmt.Errorf(`ent: validator failed for field "Address.address_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.user"`)
	}
	return nil
}

func (_u *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, address.FieldID)
		for _, f := range fields {
			if !address.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != address.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(address.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(address.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(address.FieldContactName, field.TypeString, value)
	}
	if _u.mutation.ContactNameCleared() {
		_spec.ClearField(address.FieldContactName, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(address.FieldContactPhone, field.TypeString, value)
	}
	if _u.mutation.ContactPhoneCleared() {
		_spec.ClearField(address.FieldContactPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Line1(); ok {
		_spec.SetField(address.FieldLine1, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ward(); ok {
		_spec.SetField(address.FieldWard, field.TypeString, value)
	}
	if _u.mutation.WardCleared() {
		_spec.ClearField(address.FieldWard, field.TypeString)
	}
	if value, ok := _u.mutation.District(); ok {
		_spec.SetField(address.FieldDistrict, field.TypeString, value)
	}
	if _u.mutation.DistrictCleared() {
		_spec.ClearField(address.FieldDistrict, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(address.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(address.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(address.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(address.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddressType(); ok {
		_spec.SetField(address.FieldAddressType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(address.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(address.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UserTable,
			Columns: []string{address.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UserTable,
			Columns: []string{address.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
