// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"user_service/ent/driverprofile"
	"user_service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DriverProfileDelete is the builder for deleting a DriverProfile entity.
type DriverProfileDelete struct {
	config
	hooks    []Hook
	mutation *DriverProfileMutation
}

// Where appends a list predicates to the DriverProfileDelete builder.
func (_d *DriverProfileDelete) Where(ps ...predicate.DriverProfile) *DriverProfileDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DriverProfileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DriverProfileDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DriverProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(driverprofile.Table, sqlgraph.NewFieldSpec(driverprofile.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DriverProfileDeleteOne is the builder for deleting a single DriverProfile entity.
type DriverProfileDeleteOne struct {
	_d *DriverProfileDelete
}

// Where appends a list predicates to the DriverProfileDelete builder.
func (_d *DriverProfileDeleteOne) Where(ps ...predicate.DriverProfile) *DriverProfileDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DriverProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{driverprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DriverProfileDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
