// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"user_service/ent/driverprofile"
	"user_service/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DriverProfileCreate is the builder for creating a DriverProfile entity.
type DriverProfileCreate struct {
	config
	mutation *DriverProfileMutation
	hooks    []Hook
}

// SetLicenseNumber sets the "license_number" field.
func (_c *DriverProfileCreate) SetLicenseNumber(v string) *DriverProfileCreate {
	_c.mutation.SetLicenseNumber(v)
	return _c
}

// SetIDCard sets the "id_card" field.
func (_c *DriverProfileCreate) SetIDCard(v string) *DriverProfileCreate {
	_c.mutation.SetIDCard(v)
	return _c
}

// SetRating sets the "rating" field.
func (_c *DriverProfileCreate) SetRating(v float64) *DriverProfileCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_c *DriverProfileCreate) SetNillableRating(v *float64) *DriverProfileCreate {
	if v != nil {
		_c.SetRating(*v)
	}
	return _c
}

// SetKycStatus sets the "kyc_status" field.
func (_c *DriverProfileCreate) SetKycStatus(v driverprofile.KycStatus) *DriverProfileCreate {
	_c.mutation.SetKycStatus(v)
	return _c
}

// SetNillableKycStatus sets the "kyc_status" field if the given value is not nil.
func (_c *DriverProfileCreate) SetNillableKycStatus(v *driverprofile.KycStatus) *DriverProfileCreate {
	if v != nil {
		_c.SetKycStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DriverProfileCreate) SetCreatedAt(v time.Time) *DriverProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DriverProfileCreate) SetNillableCreatedAt(v *time.Time) *DriverProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DriverProfileCreate) SetUpdatedAt(v time.Time) *DriverProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DriverProfileCreate) SetNillableUpdatedAt(v *time.Time) *DriverProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DriverProfileCreate) SetID(v uuid.UUID) *DriverProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DriverProfileCreate) SetNillableID(v *uuid.UUID) *DriverProfileCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *DriverProfileCreate) SetUserID(id uuid.UUID) *DriverProfileCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *DriverProfileCreate) SetUser(v *User) *DriverProfileCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the DriverProfileMutation object of the builder.
func (_c *DriverProfileCreate) Mutation() *DriverProfileMutation {
	return _c.mutation
}

// Save creates the DriverProfile in the database.
func (_c *DriverProfileCreate) Save(ctx context.Context) (*DriverProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DriverProfileCreate) SaveX(ctx context.Context) *DriverProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DriverProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DriverProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DriverProfileCreate) defaults() {
	if _, ok := _c.mutation.Rating(); !ok {
		v := driverprofile.DefaultRating
		_c.mutation.SetRating(v)
	}
	if _, ok := _c.mutation.KycStatus(); !ok {
		v := driverprofile.DefaultKycStatus
		_c.mutation.SetKycStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := driverprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := driverprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := driverprofile.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DriverProfileCreate) check() error {
	if _, ok := _c.mutation.LicenseNumber(); !ok {
		return &ValidationError{Name: "license_number", err: errors.New(`ent: missing required field "DriverProfile.license_number"`)}
	}
	if _, ok := _c.mutation.IDCard(); !ok {
		return &ValidationError{Name: "id_card", err: errors.New(`ent: missing required field "DriverProfile.id_card"`)}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "DriverProfile.rating"`)}
	}
	if _, ok := _c.mutation.KycStatus(); !ok {
		return &ValidationError{Name: "kyc_status", err: errors.New(`ent: missing required field "DriverProfile.kyc_status"`)}
	}
	if v, ok := _c.mutation.KycStatus(); ok {
		if err := driverprofile.KycStatusValidator(v); err != nil {
			return &ValidationError{Name: "kyc_status", err: fmt.Errorf(`ent: validator failed for field "DriverProfile.kyc_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DriverProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DriverProfile.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DriverProfile.user"`)}
	}
	return nil
}

func (_c *DriverProfileCreate) sqlSave(ctx context.Context) (*DriverProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DriverProfileCreate) createSpec() (*DriverProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &DriverProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(driverprofile.Table, sqlgraph.NewFieldSpec(driverprofile.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.LicenseNumber(); ok {
		_spec.SetField(driverprofile.FieldLicenseNumber, field.TypeString, value)
		_node.LicenseNumber = value
	}
	if value, ok := _c.mutation.IDCard(); ok {
		_spec.SetField(driverprofile.FieldIDCard, field.TypeString, value)
		_node.IDCard = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(driverprofile.FieldRating, field.TypeFloat64, value)
		_node.Rating = value
	}
	if value, ok := _c.mutation.KycStatus(); ok {
		_spec.SetField(driverprofile.FieldKycStatus, field.TypeEnum, value)
		_node.KycStatus = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(driverprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(driverprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   driverprofile.UserTable,
			Columns: []string{driverprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_driver_profile = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DriverProfileCreateBulk is the builder for creating many DriverProfile entities in bulk.
type DriverProfileCreateBulk struct {
	config
	err      error
	builders []*DriverProfileCreate
}

// Save creates the DriverProfile entities in the database.
func (_c *DriverProfileCreateBulk) Save(ctx context.Context) ([]*DriverProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DriverProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DriverProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DriverProfileCreateBulk) SaveX(ctx context.Context) []*DriverProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DriverProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DriverProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
