// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"user_service/ent/driverprofile"
	"user_service/ent/schema"
	"user_service/ent/shipperprofile"
	"user_service/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	driverprofileFields := schema.DriverProfile{}.Fields()
	_ = driverprofileFields
	// driverprofileDescRating is the schema descriptor for rating field.
	driverprofileDescRating := driverprofileFields[3].Descriptor()
	// driverprofile.DefaultRating holds the default value on creation for the rating field.
	driverprofile.DefaultRating = driverprofileDescRating.Default.(float64)
	// driverprofileDescCreatedAt is the schema descriptor for created_at field.
	driverprofileDescCreatedAt := driverprofileFields[5].Descriptor()
	// driverprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	driverprofile.DefaultCreatedAt = driverprofileDescCreatedAt.Default.(func() time.Time)
	// driverprofileDescUpdatedAt is the schema descriptor for updated_at field.
	driverprofileDescUpdatedAt := driverprofileFields[6].Descriptor()
	// driverprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	driverprofile.DefaultUpdatedAt = driverprofileDescUpdatedAt.Default.(func() time.Time)
	// driverprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	driverprofile.UpdateDefaultUpdatedAt = driverprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// driverprofileDescID is the schema descriptor for id field.
	driverprofileDescID := driverprofileFields[0].Descriptor()
	// driverprofile.DefaultID holds the default value on creation for the id field.
	driverprofile.DefaultID = driverprofileDescID.Default.(func() uuid.UUID)
	shipperprofileFields := schema.ShipperProfile{}.Fields()
	_ = shipperprofileFields
	// shipperprofileDescCreatedAt is the schema descriptor for created_at field.
	shipperprofileDescCreatedAt := shipperprofileFields[3].Descriptor()
	// shipperprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	shipperprofile.DefaultCreatedAt = shipperprofileDescCreatedAt.Default.(func() time.Time)
	// shipperprofileDescUpdatedAt is the schema descriptor for updated_at field.
	shipperprofileDescUpdatedAt := shipperprofileFields[4].Descriptor()
	// shipperprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	shipperprofile.DefaultUpdatedAt = shipperprofileDescUpdatedAt.Default.(func() time.Time)
	// shipperprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	shipperprofile.UpdateDefaultUpdatedAt = shipperprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// shipperprofileDescID is the schema descriptor for id field.
	shipperprofileDescID := shipperprofileFields[0].Descriptor()
	// shipperprofile.DefaultID holds the default value on creation for the id field.
	shipperprofile.DefaultID = shipperprofileDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
