// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"user_service/ent/shipperprofile"
	"user_service/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ShipperProfile is the model entity for the ShipperProfile schema.
type ShipperProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CompanyName holds the value of the "company_name" field.
	CompanyName string `json:"company_name,omitempty"`
	// TaxCode holds the value of the "tax_code" field.
	TaxCode string `json:"tax_code,omitempty"`
	// BusinessAddress holds the value of the "business_address" field.
	BusinessAddress string `json:"business_address,omitempty"`
	// TotalOrders holds the value of the "total_orders" field.
	TotalOrders int `json:"total_orders,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShipperProfileQuery when eager-loading is set.
	Edges        ShipperProfileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ShipperProfileEdges holds the relations/edges for other nodes in the graph.
type ShipperProfileEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShipperProfileEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ShipperProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shipperprofile.FieldTotalOrders:
			values[i] = new(sql.NullInt64)
		case shipperprofile.FieldCompanyName, shipperprofile.FieldTaxCode, shipperprofile.FieldBusinessAddress:
			values[i] = new(sql.NullString)
		case shipperprofile.FieldCreatedAt, shipperprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case shipperprofile.FieldID, shipperprofile.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ShipperProfile fields.
func (_m *ShipperProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shipperprofile.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case shipperprofile.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case shipperprofile.FieldCompanyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company_name", values[i])
			} else if value.Valid {
				_m.CompanyName = value.String
			}
		case shipperprofile.FieldTaxCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_code", values[i])
			} else if value.Valid {
				_m.TaxCode = value.String
			}
		case shipperprofile.FieldBusinessAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field business_address", values[i])
			} else if value.Valid {
				_m.BusinessAddress = value.String
			}
		case shipperprofile.FieldTotalOrders:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_orders", values[i])
			} else if value.Valid {
				_m.TotalOrders = int(value.Int64)
			}
		case shipperprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case shipperprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ShipperProfile.
// This includes values selected through modifiers, order, etc.
func (_m *ShipperProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ShipperProfile entity.
func (_m *ShipperProfile) QueryUser() *UserQuery {
	return NewShipperProfileClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ShipperProfile.
// Note that you need to call ShipperProfile.Unwrap() before calling this method if this ShipperProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ShipperProfile) Update() *ShipperProfileUpdateOne {
	return NewShipperProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ShipperProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ShipperProfile) Unwrap() *ShipperProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ShipperProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ShipperProfile) String() string {
	var builder strings.Builder
	builder.WriteString("ShipperProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("company_name=")
	builder.WriteString(_m.CompanyName)
	builder.WriteString(", ")
	builder.WriteString("tax_code=")
	builder.WriteString(_m.TaxCode)
	builder.WriteString(", ")
	builder.WriteString("business_address=")
	builder.WriteString(_m.BusinessAddress)
	builder.WriteString(", ")
	builder.WriteString("total_orders=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalOrders))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ShipperProfiles is a parsable slice of ShipperProfile.
type ShipperProfiles []*ShipperProfile
