#!/bin/bash
set -e

echo "=== CREATE VEHICLE REPLICATION FOR MASTER ==="

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $REPLICATION_USER WITH REPLICATION ENCRYPTED PASSWORD '$REPLICATION_PASSWORD';
EOSQL

FIREWALL_RULE="host replication $REPLICATION_USER 0.0.0.0/0 scram-sha-256"
echo "$FIREWALL_RULE" >> "$PGDATA/pg_hba.conf"

echo "=== CREATE VEHICLE REPLICATION FOR MASTER SUCCESSFULLY ==="
