listen_addresses = '*'
wal_level = replica
max_wal_senders = 10
max_replication = 10
# Bật chế độ Synchronous (Đồng bộ)
# Dấu '*' nghĩa là bắt buộc 1 node replica bất kỳ phải xác nhận (ACK) thì Master mới commit
synchronous_standby_names = '*'