// Code generated by ent, DO NOT EDIT.

package bids

import (
	"matching_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldUpdatedBy, v))
}

// IsDeleted applies equality check predicate on the "is_deleted" field. It's identical to IsDeletedEQ.
func IsDeleted(v bool) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldIsDeleted, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldUserID, v))
}

// VolumeM3 applies equality check predicate on the "volume_m3" field. It's identical to VolumeM3EQ.
func VolumeM3(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldVolumeM3, v))
}

// WeightKg applies equality check predicate on the "weight_kg" field. It's identical to WeightKgEQ.
func WeightKg(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldWeightKg, v))
}

// MaxPrice applies equality check predicate on the "max_price" field. It's identical to MaxPriceEQ.
func MaxPrice(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldMaxPrice, v))
}

// ZoneID applies equality check predicate on the "zone_id" field. It's identical to ZoneIDEQ.
func ZoneID(v string) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldZoneID, v))
}

// OriginLat applies equality check predicate on the "origin_lat" field. It's identical to OriginLatEQ.
func OriginLat(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldOriginLat, v))
}

// OriginLng applies equality check predicate on the "origin_lng" field. It's identical to OriginLngEQ.
func OriginLng(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldOriginLng, v))
}

// DestinationLat applies equality check predicate on the "destination_lat" field. It's identical to DestinationLatEQ.
func DestinationLat(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldDestinationLat, v))
}

// DestinationLng applies equality check predicate on the "destination_lng" field. It's identical to DestinationLngEQ.
func DestinationLng(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldDestinationLng, v))
}

// RouteID applies equality check predicate on the "route_id" field. It's identical to RouteIDEQ.
func RouteID(v []byte) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldRouteID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldCreatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldUpdatedBy, v))
}

// IsDeletedEQ applies the EQ predicate on the "is_deleted" field.
func IsDeletedEQ(v bool) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldIsDeleted, v))
}

// IsDeletedNEQ applies the NEQ predicate on the "is_deleted" field.
func IsDeletedNEQ(v bool) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldIsDeleted, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Bids {
	return predicate.Bids(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Bids {
	return predicate.Bids(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldUserID, v))
}

// VolumeM3EQ applies the EQ predicate on the "volume_m3" field.
func VolumeM3EQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldVolumeM3, v))
}

// VolumeM3NEQ applies the NEQ predicate on the "volume_m3" field.
func VolumeM3NEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldVolumeM3, v))
}

// VolumeM3In applies the In predicate on the "volume_m3" field.
func VolumeM3In(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldVolumeM3, vs...))
}

// VolumeM3NotIn applies the NotIn predicate on the "volume_m3" field.
func VolumeM3NotIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldVolumeM3, vs...))
}

// VolumeM3GT applies the GT predicate on the "volume_m3" field.
func VolumeM3GT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldVolumeM3, v))
}

// VolumeM3GTE applies the GTE predicate on the "volume_m3" field.
func VolumeM3GTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldVolumeM3, v))
}

// VolumeM3LT applies the LT predicate on the "volume_m3" field.
func VolumeM3LT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldVolumeM3, v))
}

// VolumeM3LTE applies the LTE predicate on the "volume_m3" field.
func VolumeM3LTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldVolumeM3, v))
}

// WeightKgEQ applies the EQ predicate on the "weight_kg" field.
func WeightKgEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldWeightKg, v))
}

// WeightKgNEQ applies the NEQ predicate on the "weight_kg" field.
func WeightKgNEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldWeightKg, v))
}

// WeightKgIn applies the In predicate on the "weight_kg" field.
func WeightKgIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldWeightKg, vs...))
}

// WeightKgNotIn applies the NotIn predicate on the "weight_kg" field.
func WeightKgNotIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldWeightKg, vs...))
}

// WeightKgGT applies the GT predicate on the "weight_kg" field.
func WeightKgGT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldWeightKg, v))
}

// WeightKgGTE applies the GTE predicate on the "weight_kg" field.
func WeightKgGTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldWeightKg, v))
}

// WeightKgLT applies the LT predicate on the "weight_kg" field.
func WeightKgLT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldWeightKg, v))
}

// WeightKgLTE applies the LTE predicate on the "weight_kg" field.
func WeightKgLTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldWeightKg, v))
}

// MaxPriceEQ applies the EQ predicate on the "max_price" field.
func MaxPriceEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldMaxPrice, v))
}

// MaxPriceNEQ applies the NEQ predicate on the "max_price" field.
func MaxPriceNEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldMaxPrice, v))
}

// MaxPriceIn applies the In predicate on the "max_price" field.
func MaxPriceIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldMaxPrice, vs...))
}

// MaxPriceNotIn applies the NotIn predicate on the "max_price" field.
func MaxPriceNotIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldMaxPrice, vs...))
}

// MaxPriceGT applies the GT predicate on the "max_price" field.
func MaxPriceGT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldMaxPrice, v))
}

// MaxPriceGTE applies the GTE predicate on the "max_price" field.
func MaxPriceGTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldMaxPrice, v))
}

// MaxPriceLT applies the LT predicate on the "max_price" field.
func MaxPriceLT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldMaxPrice, v))
}

// MaxPriceLTE applies the LTE predicate on the "max_price" field.
func MaxPriceLTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldMaxPrice, v))
}

// MaxPriceIsNil applies the IsNil predicate on the "max_price" field.
func MaxPriceIsNil() predicate.Bids {
	return predicate.Bids(sql.FieldIsNull(FieldMaxPrice))
}

// MaxPriceNotNil applies the NotNil predicate on the "max_price" field.
func MaxPriceNotNil() predicate.Bids {
	return predicate.Bids(sql.FieldNotNull(FieldMaxPrice))
}

// ZoneIDEQ applies the EQ predicate on the "zone_id" field.
func ZoneIDEQ(v string) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldZoneID, v))
}

// ZoneIDNEQ applies the NEQ predicate on the "zone_id" field.
func ZoneIDNEQ(v string) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldZoneID, v))
}

// ZoneIDIn applies the In predicate on the "zone_id" field.
func ZoneIDIn(vs ...string) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldZoneID, vs...))
}

// ZoneIDNotIn applies the NotIn predicate on the "zone_id" field.
func ZoneIDNotIn(vs ...string) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldZoneID, vs...))
}

// ZoneIDGT applies the GT predicate on the "zone_id" field.
func ZoneIDGT(v string) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldZoneID, v))
}

// ZoneIDGTE applies the GTE predicate on the "zone_id" field.
func ZoneIDGTE(v string) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldZoneID, v))
}

// ZoneIDLT applies the LT predicate on the "zone_id" field.
func ZoneIDLT(v string) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldZoneID, v))
}

// ZoneIDLTE applies the LTE predicate on the "zone_id" field.
func ZoneIDLTE(v string) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldZoneID, v))
}

// ZoneIDContains applies the Contains predicate on the "zone_id" field.
func ZoneIDContains(v string) predicate.Bids {
	return predicate.Bids(sql.FieldContains(FieldZoneID, v))
}

// ZoneIDHasPrefix applies the HasPrefix predicate on the "zone_id" field.
func ZoneIDHasPrefix(v string) predicate.Bids {
	return predicate.Bids(sql.FieldHasPrefix(FieldZoneID, v))
}

// ZoneIDHasSuffix applies the HasSuffix predicate on the "zone_id" field.
func ZoneIDHasSuffix(v string) predicate.Bids {
	return predicate.Bids(sql.FieldHasSuffix(FieldZoneID, v))
}

// ZoneIDEqualFold applies the EqualFold predicate on the "zone_id" field.
func ZoneIDEqualFold(v string) predicate.Bids {
	return predicate.Bids(sql.FieldEqualFold(FieldZoneID, v))
}

// ZoneIDContainsFold applies the ContainsFold predicate on the "zone_id" field.
func ZoneIDContainsFold(v string) predicate.Bids {
	return predicate.Bids(sql.FieldContainsFold(FieldZoneID, v))
}

// OriginLatEQ applies the EQ predicate on the "origin_lat" field.
func OriginLatEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldOriginLat, v))
}

// OriginLatNEQ applies the NEQ predicate on the "origin_lat" field.
func OriginLatNEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldOriginLat, v))
}

// OriginLatIn applies the In predicate on the "origin_lat" field.
func OriginLatIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldOriginLat, vs...))
}

// OriginLatNotIn applies the NotIn predicate on the "origin_lat" field.
func OriginLatNotIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldOriginLat, vs...))
}

// OriginLatGT applies the GT predicate on the "origin_lat" field.
func OriginLatGT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldOriginLat, v))
}

// OriginLatGTE applies the GTE predicate on the "origin_lat" field.
func OriginLatGTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldOriginLat, v))
}

// OriginLatLT applies the LT predicate on the "origin_lat" field.
func OriginLatLT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldOriginLat, v))
}

// OriginLatLTE applies the LTE predicate on the "origin_lat" field.
func OriginLatLTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldOriginLat, v))
}

// OriginLngEQ applies the EQ predicate on the "origin_lng" field.
func OriginLngEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldOriginLng, v))
}

// OriginLngNEQ applies the NEQ predicate on the "origin_lng" field.
func OriginLngNEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldOriginLng, v))
}

// OriginLngIn applies the In predicate on the "origin_lng" field.
func OriginLngIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldOriginLng, vs...))
}

// OriginLngNotIn applies the NotIn predicate on the "origin_lng" field.
func OriginLngNotIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldOriginLng, vs...))
}

// OriginLngGT applies the GT predicate on the "origin_lng" field.
func OriginLngGT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldOriginLng, v))
}

// OriginLngGTE applies the GTE predicate on the "origin_lng" field.
func OriginLngGTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldOriginLng, v))
}

// OriginLngLT applies the LT predicate on the "origin_lng" field.
func OriginLngLT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldOriginLng, v))
}

// OriginLngLTE applies the LTE predicate on the "origin_lng" field.
func OriginLngLTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldOriginLng, v))
}

// DestinationLatEQ applies the EQ predicate on the "destination_lat" field.
func DestinationLatEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldDestinationLat, v))
}

// DestinationLatNEQ applies the NEQ predicate on the "destination_lat" field.
func DestinationLatNEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldDestinationLat, v))
}

// DestinationLatIn applies the In predicate on the "destination_lat" field.
func DestinationLatIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldDestinationLat, vs...))
}

// DestinationLatNotIn applies the NotIn predicate on the "destination_lat" field.
func DestinationLatNotIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldDestinationLat, vs...))
}

// DestinationLatGT applies the GT predicate on the "destination_lat" field.
func DestinationLatGT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldDestinationLat, v))
}

// DestinationLatGTE applies the GTE predicate on the "destination_lat" field.
func DestinationLatGTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldDestinationLat, v))
}

// DestinationLatLT applies the LT predicate on the "destination_lat" field.
func DestinationLatLT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldDestinationLat, v))
}

// DestinationLatLTE applies the LTE predicate on the "destination_lat" field.
func DestinationLatLTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldDestinationLat, v))
}

// DestinationLngEQ applies the EQ predicate on the "destination_lng" field.
func DestinationLngEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldDestinationLng, v))
}

// DestinationLngNEQ applies the NEQ predicate on the "destination_lng" field.
func DestinationLngNEQ(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldDestinationLng, v))
}

// DestinationLngIn applies the In predicate on the "destination_lng" field.
func DestinationLngIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldDestinationLng, vs...))
}

// DestinationLngNotIn applies the NotIn predicate on the "destination_lng" field.
func DestinationLngNotIn(vs ...float64) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldDestinationLng, vs...))
}

// DestinationLngGT applies the GT predicate on the "destination_lng" field.
func DestinationLngGT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldDestinationLng, v))
}

// DestinationLngGTE applies the GTE predicate on the "destination_lng" field.
func DestinationLngGTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldDestinationLng, v))
}

// DestinationLngLT applies the LT predicate on the "destination_lng" field.
func DestinationLngLT(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldDestinationLng, v))
}

// DestinationLngLTE applies the LTE predicate on the "destination_lng" field.
func DestinationLngLTE(v float64) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldDestinationLng, v))
}

// RouteIDEQ applies the EQ predicate on the "route_id" field.
func RouteIDEQ(v []byte) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldRouteID, v))
}

// RouteIDNEQ applies the NEQ predicate on the "route_id" field.
func RouteIDNEQ(v []byte) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldRouteID, v))
}

// RouteIDIn applies the In predicate on the "route_id" field.
func RouteIDIn(vs ...[]byte) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldRouteID, vs...))
}

// RouteIDNotIn applies the NotIn predicate on the "route_id" field.
func RouteIDNotIn(vs ...[]byte) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldRouteID, vs...))
}

// RouteIDGT applies the GT predicate on the "route_id" field.
func RouteIDGT(v []byte) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldRouteID, v))
}

// RouteIDGTE applies the GTE predicate on the "route_id" field.
func RouteIDGTE(v []byte) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldRouteID, v))
}

// RouteIDLT applies the LT predicate on the "route_id" field.
func RouteIDLT(v []byte) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldRouteID, v))
}

// RouteIDLTE applies the LTE predicate on the "route_id" field.
func RouteIDLTE(v []byte) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldRouteID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.Bids {
	return predicate.Bids(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.Bids {
	return predicate.Bids(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.Bids {
	return predicate.Bids(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.Bids {
	return predicate.Bids(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.Bids {
	return predicate.Bids(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.Bids {
	return predicate.Bids(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.Bids {
	return predicate.Bids(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.Bids {
	return predicate.Bids(sql.FieldLTE(FieldStatus, v))
}

// HasMatches applies the HasEdge predicate on the "matches" edge.
func HasMatches() predicate.Bids {
	return predicate.Bids(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MatchesTable, MatchesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMatchesWith applies the HasEdge predicate on the "matches" edge with a given conditions (other predicates).
func HasMatchesWith(preds ...predicate.Match) predicate.Bids {
	return predicate.Bids(func(s *sql.Selector) {
		step := newMatchesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBidsRequirements applies the HasEdge predicate on the "bids_requirements" edge.
func HasBidsRequirements() predicate.Bids {
	return predicate.Bids(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BidsRequirementsTable, BidsRequirementsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBidsRequirementsWith applies the HasEdge predicate on the "bids_requirements" edge with a given conditions (other predicates).
func HasBidsRequirementsWith(preds ...predicate.Bids_Requirements) predicate.Bids {
	return predicate.Bids(func(s *sql.Selector) {
		step := newBidsRequirementsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bids) predicate.Bids {
	return predicate.Bids(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bids) predicate.Bids {
	return predicate.Bids(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bids) predicate.Bids {
	return predicate.Bids(sql.NotPredicates(p))
}
