// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notification_service/ent/notificationpreference"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// NotificationPreferenceCreate is the builder for creating a NotificationPreference entity.
type NotificationPreferenceCreate struct {
	config
	mutation *NotificationPreferenceMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *NotificationPreferenceCreate) SetUserID(v uuid.UUID) *NotificationPreferenceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetInAppEnabled sets the "in_app_enabled" field.
func (_c *NotificationPreferenceCreate) SetInAppEnabled(v bool) *NotificationPreferenceCreate {
	_c.mutation.SetInAppEnabled(v)
	return _c
}

// SetNillableInAppEnabled sets the "in_app_enabled" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableInAppEnabled(v *bool) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetInAppEnabled(*v)
	}
	return _c
}

// SetPushEnabled sets the "push_enabled" field.
func (_c *NotificationPreferenceCreate) SetPushEnabled(v bool) *NotificationPreferenceCreate {
	_c.mutation.SetPushEnabled(v)
	return _c
}

// SetNillablePushEnabled sets the "push_enabled" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillablePushEnabled(v *bool) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetPushEnabled(*v)
	}
	return _c
}

// SetEmailEnabled sets the "email_enabled" field.
func (_c *NotificationPreferenceCreate) SetEmailEnabled(v bool) *NotificationPreferenceCreate {
	_c.mutation.SetEmailEnabled(v)
	return _c
}

// SetNillableEmailEnabled sets the "email_enabled" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableEmailEnabled(v *bool) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetEmailEnabled(*v)
	}
	return _c
}

// SetSmsEnabled sets the "sms_enabled" field.
func (_c *NotificationPreferenceCreate) SetSmsEnabled(v bool) *NotificationPreferenceCreate {
	_c.mutation.SetSmsEnabled(v)
	return _c
}

// SetNillableSmsEnabled sets the "sms_enabled" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableSmsEnabled(v *bool) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetSmsEnabled(*v)
	}
	return _c
}

// SetMatchEventsEnabled sets the "match_events_enabled" field.
func (_c *NotificationPreferenceCreate) SetMatchEventsEnabled(v bool) *NotificationPreferenceCreate {
	_c.mutation.SetMatchEventsEnabled(v)
	return _c
}

// SetNillableMatchEventsEnabled sets the "match_events_enabled" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableMatchEventsEnabled(v *bool) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetMatchEventsEnabled(*v)
	}
	return _c
}

// SetPromotionEnabled sets the "promotion_enabled" field.
func (_c *NotificationPreferenceCreate) SetPromotionEnabled(v bool) *NotificationPreferenceCreate {
	_c.mutation.SetPromotionEnabled(v)
	return _c
}

// SetNillablePromotionEnabled sets the "promotion_enabled" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillablePromotionEnabled(v *bool) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetPromotionEnabled(*v)
	}
	return _c
}

// SetQuietHoursStart sets the "quiet_hours_start" field.
func (_c *NotificationPreferenceCreate) SetQuietHoursStart(v string) *NotificationPreferenceCreate {
	_c.mutation.SetQuietHoursStart(v)
	return _c
}

// SetNillableQuietHoursStart sets the "quiet_hours_start" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableQuietHoursStart(v *string) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetQuietHoursStart(*v)
	}
	return _c
}

// SetQuietHoursEnd sets the "quiet_hours_end" field.
func (_c *NotificationPreferenceCreate) SetQuietHoursEnd(v string) *NotificationPreferenceCreate {
	_c.mutation.SetQuietHoursEnd(v)
	return _c
}

// SetNillableQuietHoursEnd sets the "quiet_hours_end" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableQuietHoursEnd(v *string) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetQuietHoursEnd(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationPreferenceCreate) SetCreatedAt(v time.Time) *NotificationPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableCreatedAt(v *time.Time) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationPreferenceCreate) SetUpdatedAt(v time.Time) *NotificationPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableUpdatedAt(v *time.Time) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationPreferenceCreate) SetID(v uuid.UUID) *NotificationPreferenceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotificationPreferenceCreate) SetNillableID(v *uuid.UUID) *NotificationPreferenceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the NotificationPreferenceMutation object of the builder.
func (_c *NotificationPreferenceCreate) Mutation() *NotificationPreferenceMutation {
	return _c.mutation
}

// Save creates the NotificationPreference in the database.
func (_c *NotificationPreferenceCreate) Save(ctx context.Context) (*NotificationPreference, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationPreferenceCreate) SaveX(ctx context.Context) *NotificationPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationPreferenceCreate) defaults() {
	if _, ok := _c.mutation.InAppEnabled(); !ok {
		v := notificationpreference.DefaultInAppEnabled
		_c.mutation.SetInAppEnabled(v)
	}
	if _, ok := _c.mutation.PushEnabled(); !ok {
		v := notificationpreference.DefaultPushEnabled
		_c.mutation.SetPushEnabled(v)
	}
	if _, ok := _c.mutation.EmailEnabled(); !ok {
		v := notificationpreference.DefaultEmailEnabled
		_c.mutation.SetEmailEnabled(v)
	}
	if _, ok := _c.mutation.SmsEnabled(); !ok {
		v := notificationpreference.DefaultSmsEnabled
		_c.mutation.SetSmsEnabled(v)
	}
	if _, ok := _c.mutation.MatchEventsEnabled(); !ok {
		v := notificationpreference.DefaultMatchEventsEnabled
		_c.mutation.SetMatchEventsEnabled(v)
	}
	if _, ok := _c.mutation.PromotionEnabled(); !ok {
		v := notificationpreference.DefaultPromotionEnabled
		_c.mutation.SetPromotionEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notificationpreference.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notificationpreference.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := notificationpreference.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationPreferenceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NotificationPreference.user_id"`)}
	}
	if _, ok := _c.mutation.InAppEnabled(); !ok {
		return &ValidationError{Name: "in_app_enabled", err: errors.New(`ent: missing required field "NotificationPreference.in_app_enabled"`)}
	}
	if _, ok := _c.mutation.PushEnabled(); !ok {
		return &ValidationError{Name: "push_enabled", err: errors.New(`ent: missing required field "NotificationPreference.push_enabled"`)}
	}
	if _, ok := _c.mutation.EmailEnabled(); !ok {
		return &ValidationError{Name: "email_enabled", err: errors.New(`ent: missing required field "NotificationPreference.email_enabled"`)}
	}
	if _, ok := _c.mutation.SmsEnabled(); !ok {
		return &ValidationError{Name: "sms_enabled", err: errors.New(`ent: missing required field "NotificationPreference.sms_enabled"`)}
	}
	if _, ok := _c.mutation.MatchEventsEnabled(); !ok {
		return &ValidationError{Name: "match_events_enabled", err: errors.New(`ent: missing required field "NotificationPreference.match_events_enabled"`)}
	}
	if _, ok := _c.mutation.PromotionEnabled(); !ok {
		return &ValidationError{Name: "promotion_enabled", err: errors.New(`ent: missing required field "NotificationPreference.promotion_enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationPreference.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationPreference.updated_at"`)}
	}
	return nil
}

func (_c *NotificationPreferenceCreate) sqlSave(ctx context.Context) (*NotificationPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationPreferenceCreate) createSpec() (*NotificationPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationpreference.Table, sqlgraph.NewFieldSpec(notificationpreference.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(notificationpreference.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.InAppEnabled(); ok {
		_spec.SetField(notificationpreference.FieldInAppEnabled, field.TypeBool, value)
		_node.InAppEnabled = value
	}
	if value, ok := _c.mutation.PushEnabled(); ok {
		_spec.SetField(notificationpreference.FieldPushEnabled, field.TypeBool, value)
		_node.PushEnabled = value
	}
	if value, ok := _c.mutation.EmailEnabled(); ok {
		_spec.SetField(notificationpreference.FieldEmailEnabled, field.TypeBool, value)
		_node.EmailEnabled = value
	}
	if value, ok := _c.mutation.SmsEnabled(); ok {
		_spec.SetField(notificationpreference.FieldSmsEnabled, field.TypeBool, value)
		_node.SmsEnabled = value
	}
	if value, ok := _c.mutation.MatchEventsEnabled(); ok {
		_spec.SetField(notificationpreference.FieldMatchEventsEnabled, field.TypeBool, value)
		_node.MatchEventsEnabled = value
	}
	if value, ok := _c.mutation.PromotionEnabled(); ok {
		_spec.SetField(notificationpreference.FieldPromotionEnabled, field.TypeBool, value)
		_node.PromotionEnabled = value
	}
	if value, ok := _c.mutation.QuietHoursStart(); ok {
		_spec.SetField(notificationpreference.FieldQuietHoursStart, field.TypeString, value)
		_node.QuietHoursStart = value
	}
	if value, ok := _c.mutation.QuietHoursEnd(); ok {
		_spec.SetField(notificationpreference.FieldQuietHoursEnd, field.TypeString, value)
		_node.QuietHoursEnd = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationpreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationpreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// NotificationPreferenceCreateBulk is the builder for creating many NotificationPreference entities in bulk.
type NotificationPreferenceCreateBulk struct {
	config
	err      error
	builders []*NotificationPreferenceCreate
}

// Save creates the NotificationPreference entities in the database.
func (_c *NotificationPreferenceCreateBulk) Save(ctx context.Context) ([]*NotificationPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationPreferenceCreateBulk) SaveX(ctx context.Context) []*NotificationPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
