// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"notification_service/ent/notificationtemplate"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// NotificationTemplate is the model entity for the NotificationTemplate schema.
type NotificationTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel notificationtemplate.Channel `json:"channel,omitempty"`
	// Locale holds the value of the "locale" field.
	Locale string `json:"locale,omitempty"`
	// TitleTemplate holds the value of the "title_template" field.
	TitleTemplate string `json:"title_template,omitempty"`
	// BodyTemplate holds the value of the "body_template" field.
	BodyTemplate string `json:"body_template,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationtemplate.FieldIsActive:
			values[i] = new(sql.NullBool)
		case notificationtemplate.FieldCode, notificationtemplate.FieldName, notificationtemplate.FieldChannel, notificationtemplate.FieldLocale, notificationtemplate.FieldTitleTemplate, notificationtemplate.FieldBodyTemplate:
			values[i] = new(sql.NullString)
		case notificationtemplate.FieldCreatedAt, notificationtemplate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case notificationtemplate.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationTemplate fields.
func (_m *NotificationTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationtemplate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case notificationtemplate.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case notificationtemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case notificationtemplate.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = notificationtemplate.Channel(value.String)
			}
		case notificationtemplate.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case notificationtemplate.FieldTitleTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_template", values[i])
			} else if value.Valid {
				_m.TitleTemplate = value.String
			}
		case notificationtemplate.FieldBodyTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body_template", values[i])
			} else if value.Valid {
				_m.BodyTemplate = value.String
			}
		case notificationtemplate.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case notificationtemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case notificationtemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NotificationTemplate.
// Note that you need to call NotificationTemplate.Unwrap() before calling this method if this NotificationTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationTemplate) Update() *NotificationTemplateUpdateOne {
	return NewNotificationTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationTemplate) Unwrap() *NotificationTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(fmt.Sprintf("%v", _m.Channel))
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("title_template=")
	builder.WriteString(_m.TitleTemplate)
	builder.WriteString(", ")
	builder.WriteString("body_template=")
	builder.WriteString(_m.BodyTemplate)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationTemplates is a parsable slice of NotificationTemplate.
type NotificationTemplates []*NotificationTemplate
