// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"matching_service/ent/bids"
	"matching_service/ent/bids_requirements"
	"matching_service/ent/match"
	"matching_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BidsUpdate is the builder for updating Bids entities.
type BidsUpdate struct {
	config
	hooks    []Hook
	mutation *BidsMutation
}

// Where appends a list predicates to the BidsUpdate builder.
func (_u *BidsUpdate) Where(ps ...predicate.Bids) *BidsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *BidsUpdate) SetCreatedBy(v uuid.UUID) *BidsUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableCreatedBy(v *uuid.UUID) *BidsUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BidsUpdate) SetUpdatedAt(v time.Time) *BidsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BidsUpdate) SetUpdatedBy(v uuid.UUID) *BidsUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableUpdatedBy(v *uuid.UUID) *BidsUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *BidsUpdate) SetIsDeleted(v bool) *BidsUpdate {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableIsDeleted(v *bool) *BidsUpdate {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BidsUpdate) SetDeletedAt(v time.Time) *BidsUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableDeletedAt(v *time.Time) *BidsUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BidsUpdate) ClearDeletedAt() *BidsUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetShipperID sets the "shipper_id" field.
func (_u *BidsUpdate) SetShipperID(v uuid.UUID) *BidsUpdate {
	_u.mutation.SetShipperID(v)
	return _u
}

// SetNillableShipperID sets the "shipper_id" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableShipperID(v *uuid.UUID) *BidsUpdate {
	if v != nil {
		_u.SetShipperID(*v)
	}
	return _u
}

// SetShipperPhone sets the "shipper_phone" field.
func (_u *BidsUpdate) SetShipperPhone(v string) *BidsUpdate {
	_u.mutation.SetShipperPhone(v)
	return _u
}

// SetNillableShipperPhone sets the "shipper_phone" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableShipperPhone(v *string) *BidsUpdate {
	if v != nil {
		_u.SetShipperPhone(*v)
	}
	return _u
}

// SetShipperMail sets the "shipper_mail" field.
func (_u *BidsUpdate) SetShipperMail(v string) *BidsUpdate {
	_u.mutation.SetShipperMail(v)
	return _u
}

// SetNillableShipperMail sets the "shipper_mail" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableShipperMail(v *string) *BidsUpdate {
	if v != nil {
		_u.SetShipperMail(*v)
	}
	return _u
}

// SetConsigneeID sets the "consignee_id" field.
func (_u *BidsUpdate) SetConsigneeID(v uuid.UUID) *BidsUpdate {
	_u.mutation.SetConsigneeID(v)
	return _u
}

// SetNillableConsigneeID sets the "consignee_id" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableConsigneeID(v *uuid.UUID) *BidsUpdate {
	if v != nil {
		_u.SetConsigneeID(*v)
	}
	return _u
}

// SetConsigneePhone sets the "consignee_phone" field.
func (_u *BidsUpdate) SetConsigneePhone(v string) *BidsUpdate {
	_u.mutation.SetConsigneePhone(v)
	return _u
}

// SetNillableConsigneePhone sets the "consignee_phone" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableConsigneePhone(v *string) *BidsUpdate {
	if v != nil {
		_u.SetConsigneePhone(*v)
	}
	return _u
}

// SetConsigneeMail sets the "consignee_mail" field.
func (_u *BidsUpdate) SetConsigneeMail(v string) *BidsUpdate {
	_u.mutation.SetConsigneeMail(v)
	return _u
}

// SetNillableConsigneeMail sets the "consignee_mail" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableConsigneeMail(v *string) *BidsUpdate {
	if v != nil {
		_u.SetConsigneeMail(*v)
	}
	return _u
}

// SetVolumeM3 sets the "volume_m3" field.
func (_u *BidsUpdate) SetVolumeM3(v float64) *BidsUpdate {
	_u.mutation.ResetVolumeM3()
	_u.mutation.SetVolumeM3(v)
	return _u
}

// SetNillableVolumeM3 sets the "volume_m3" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableVolumeM3(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetVolumeM3(*v)
	}
	return _u
}

// AddVolumeM3 adds value to the "volume_m3" field.
func (_u *BidsUpdate) AddVolumeM3(v float64) *BidsUpdate {
	_u.mutation.AddVolumeM3(v)
	return _u
}

// SetWeightKg sets the "weight_kg" field.
func (_u *BidsUpdate) SetWeightKg(v float64) *BidsUpdate {
	_u.mutation.ResetWeightKg()
	_u.mutation.SetWeightKg(v)
	return _u
}

// SetNillableWeightKg sets the "weight_kg" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableWeightKg(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetWeightKg(*v)
	}
	return _u
}

// AddWeightKg adds value to the "weight_kg" field.
func (_u *BidsUpdate) AddWeightKg(v float64) *BidsUpdate {
	_u.mutation.AddWeightKg(v)
	return _u
}

// SetMaxPrice sets the "max_price" field.
func (_u *BidsUpdate) SetMaxPrice(v float64) *BidsUpdate {
	_u.mutation.ResetMaxPrice()
	_u.mutation.SetMaxPrice(v)
	return _u
}

// SetNillableMaxPrice sets the "max_price" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableMaxPrice(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetMaxPrice(*v)
	}
	return _u
}

// AddMaxPrice adds value to the "max_price" field.
func (_u *BidsUpdate) AddMaxPrice(v float64) *BidsUpdate {
	_u.mutation.AddMaxPrice(v)
	return _u
}

// ClearMaxPrice clears the value of the "max_price" field.
func (_u *BidsUpdate) ClearMaxPrice() *BidsUpdate {
	_u.mutation.ClearMaxPrice()
	return _u
}

// SetCargoValue sets the "cargo_value" field.
func (_u *BidsUpdate) SetCargoValue(v float64) *BidsUpdate {
	_u.mutation.ResetCargoValue()
	_u.mutation.SetCargoValue(v)
	return _u
}

// SetNillableCargoValue sets the "cargo_value" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableCargoValue(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetCargoValue(*v)
	}
	return _u
}

// AddCargoValue adds value to the "cargo_value" field.
func (_u *BidsUpdate) AddCargoValue(v float64) *BidsUpdate {
	_u.mutation.AddCargoValue(v)
	return _u
}

// SetRequiredDeposit sets the "required_deposit" field.
func (_u *BidsUpdate) SetRequiredDeposit(v float64) *BidsUpdate {
	_u.mutation.ResetRequiredDeposit()
	_u.mutation.SetRequiredDeposit(v)
	return _u
}

// SetNillableRequiredDeposit sets the "required_deposit" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableRequiredDeposit(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetRequiredDeposit(*v)
	}
	return _u
}

// AddRequiredDeposit adds value to the "required_deposit" field.
func (_u *BidsUpdate) AddRequiredDeposit(v float64) *BidsUpdate {
	_u.mutation.AddRequiredDeposit(v)
	return _u
}

// SetDesiredDeposit sets the "desired_deposit" field.
func (_u *BidsUpdate) SetDesiredDeposit(v float64) *BidsUpdate {
	_u.mutation.ResetDesiredDeposit()
	_u.mutation.SetDesiredDeposit(v)
	return _u
}

// SetNillableDesiredDeposit sets the "desired_deposit" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableDesiredDeposit(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetDesiredDeposit(*v)
	}
	return _u
}

// AddDesiredDeposit adds value to the "desired_deposit" field.
func (_u *BidsUpdate) AddDesiredDeposit(v float64) *BidsUpdate {
	_u.mutation.AddDesiredDeposit(v)
	return _u
}

// SetZoneID sets the "zone_id" field.
func (_u *BidsUpdate) SetZoneID(v string) *BidsUpdate {
	_u.mutation.SetZoneID(v)
	return _u
}

// SetNillableZoneID sets the "zone_id" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableZoneID(v *string) *BidsUpdate {
	if v != nil {
		_u.SetZoneID(*v)
	}
	return _u
}

// SetOriginLat sets the "origin_lat" field.
func (_u *BidsUpdate) SetOriginLat(v float64) *BidsUpdate {
	_u.mutation.ResetOriginLat()
	_u.mutation.SetOriginLat(v)
	return _u
}

// SetNillableOriginLat sets the "origin_lat" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableOriginLat(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetOriginLat(*v)
	}
	return _u
}

// AddOriginLat adds value to the "origin_lat" field.
func (_u *BidsUpdate) AddOriginLat(v float64) *BidsUpdate {
	_u.mutation.AddOriginLat(v)
	return _u
}

// SetOriginLng sets the "origin_lng" field.
func (_u *BidsUpdate) SetOriginLng(v float64) *BidsUpdate {
	_u.mutation.ResetOriginLng()
	_u.mutation.SetOriginLng(v)
	return _u
}

// SetNillableOriginLng sets the "origin_lng" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableOriginLng(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetOriginLng(*v)
	}
	return _u
}

// AddOriginLng adds value to the "origin_lng" field.
func (_u *BidsUpdate) AddOriginLng(v float64) *BidsUpdate {
	_u.mutation.AddOriginLng(v)
	return _u
}

// SetDestinationLat sets the "destination_lat" field.
func (_u *BidsUpdate) SetDestinationLat(v float64) *BidsUpdate {
	_u.mutation.ResetDestinationLat()
	_u.mutation.SetDestinationLat(v)
	return _u
}

// SetNillableDestinationLat sets the "destination_lat" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableDestinationLat(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetDestinationLat(*v)
	}
	return _u
}

// AddDestinationLat adds value to the "destination_lat" field.
func (_u *BidsUpdate) AddDestinationLat(v float64) *BidsUpdate {
	_u.mutation.AddDestinationLat(v)
	return _u
}

// SetDestinationLng sets the "destination_lng" field.
func (_u *BidsUpdate) SetDestinationLng(v float64) *BidsUpdate {
	_u.mutation.ResetDestinationLng()
	_u.mutation.SetDestinationLng(v)
	return _u
}

// SetNillableDestinationLng sets the "destination_lng" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableDestinationLng(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetDestinationLng(*v)
	}
	return _u
}

// AddDestinationLng adds value to the "destination_lng" field.
func (_u *BidsUpdate) AddDestinationLng(v float64) *BidsUpdate {
	_u.mutation.AddDestinationLng(v)
	return _u
}

// SetOfferedPrice sets the "offered_price" field.
func (_u *BidsUpdate) SetOfferedPrice(v float64) *BidsUpdate {
	_u.mutation.ResetOfferedPrice()
	_u.mutation.SetOfferedPrice(v)
	return _u
}

// SetNillableOfferedPrice sets the "offered_price" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableOfferedPrice(v *float64) *BidsUpdate {
	if v != nil {
		_u.SetOfferedPrice(*v)
	}
	return _u
}

// AddOfferedPrice adds value to the "offered_price" field.
func (_u *BidsUpdate) AddOfferedPrice(v float64) *BidsUpdate {
	_u.mutation.AddOfferedPrice(v)
	return _u
}

// ClearOfferedPrice clears the value of the "offered_price" field.
func (_u *BidsUpdate) ClearOfferedPrice() *BidsUpdate {
	_u.mutation.ClearOfferedPrice()
	return _u
}

// SetOfferedAskID sets the "offered_ask_id" field.
func (_u *BidsUpdate) SetOfferedAskID(v uuid.UUID) *BidsUpdate {
	_u.mutation.SetOfferedAskID(v)
	return _u
}

// SetNillableOfferedAskID sets the "offered_ask_id" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableOfferedAskID(v *uuid.UUID) *BidsUpdate {
	if v != nil {
		_u.SetOfferedAskID(*v)
	}
	return _u
}

// ClearOfferedAskID clears the value of the "offered_ask_id" field.
func (_u *BidsUpdate) ClearOfferedAskID() *BidsUpdate {
	_u.mutation.ClearOfferedAskID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BidsUpdate) SetStatus(v int8) *BidsUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableStatus(v *int8) *BidsUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *BidsUpdate) AddStatus(v int8) *BidsUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BidsUpdate) SetExpiresAt(v time.Time) *BidsUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BidsUpdate) SetNillableExpiresAt(v *time.Time) *BidsUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *BidsUpdate) ClearExpiresAt() *BidsUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// AddMatchIDs adds the "matches" edge to the Match entity by IDs.
func (_u *BidsUpdate) AddMatchIDs(ids ...uuid.UUID) *BidsUpdate {
	_u.mutation.AddMatchIDs(ids...)
	return _u
}

// AddMatches adds the "matches" edges to the Match entity.
func (_u *BidsUpdate) AddMatches(v ...*Match) *BidsUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMatchIDs(ids...)
}

// AddBidsRequirementIDs adds the "bids_requirements" edge to the Bids_Requirements entity by IDs.
func (_u *BidsUpdate) AddBidsRequirementIDs(ids ...uuid.UUID) *BidsUpdate {
	_u.mutation.AddBidsRequirementIDs(ids...)
	return _u
}

// AddBidsRequirements adds the "bids_requirements" edges to the Bids_Requirements entity.
func (_u *BidsUpdate) AddBidsRequirements(v ...*Bids_Requirements) *BidsUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBidsRequirementIDs(ids...)
}

// Mutation returns the BidsMutation object of the builder.
func (_u *BidsUpdate) Mutation() *BidsMutation {
	return _u.mutation
}

// ClearMatches clears all "matches" edges to the Match entity.
func (_u *BidsUpdate) ClearMatches() *BidsUpdate {
	_u.mutation.ClearMatches()
	return _u
}

// RemoveMatchIDs removes the "matches" edge to Match entities by IDs.
func (_u *BidsUpdate) RemoveMatchIDs(ids ...uuid.UUID) *BidsUpdate {
	_u.mutation.RemoveMatchIDs(ids...)
	return _u
}

// RemoveMatches removes "matches" edges to Match entities.
func (_u *BidsUpdate) RemoveMatches(v ...*Match) *BidsUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMatchIDs(ids...)
}

// ClearBidsRequirements clears all "bids_requirements" edges to the Bids_Requirements entity.
func (_u *BidsUpdate) ClearBidsRequirements() *BidsUpdate {
	_u.mutation.ClearBidsRequirements()
	return _u
}

// RemoveBidsRequirementIDs removes the "bids_requirements" edge to Bids_Requirements entities by IDs.
func (_u *BidsUpdate) RemoveBidsRequirementIDs(ids ...uuid.UUID) *BidsUpdate {
	_u.mutation.RemoveBidsRequirementIDs(ids...)
	return _u
}

// RemoveBidsRequirements removes "bids_requirements" edges to Bids_Requirements entities.
func (_u *BidsUpdate) RemoveBidsRequirements(v ...*Bids_Requirements) *BidsUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBidsRequirementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BidsUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BidsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BidsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BidsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BidsUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if bids.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized bids.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := bids.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *BidsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bids.Table, bids.Columns, sqlgraph.NewFieldSpec(bids.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(bids.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bids.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(bids.FieldUpdatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(bids.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(bids.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(bids.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ShipperID(); ok {
		_spec.SetField(bids.FieldShipperID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ShipperPhone(); ok {
		_spec.SetField(bids.FieldShipperPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShipperMail(); ok {
		_spec.SetField(bids.FieldShipperMail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsigneeID(); ok {
		_spec.SetField(bids.FieldConsigneeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ConsigneePhone(); ok {
		_spec.SetField(bids.FieldConsigneePhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsigneeMail(); ok {
		_spec.SetField(bids.FieldConsigneeMail, field.TypeString, value)
	}
	if value, ok := _u.mutation.VolumeM3(); ok {
		_spec.SetField(bids.FieldVolumeM3, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVolumeM3(); ok {
		_spec.AddField(bids.FieldVolumeM3, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeightKg(); ok {
		_spec.SetField(bids.FieldWeightKg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeightKg(); ok {
		_spec.AddField(bids.FieldWeightKg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxPrice(); ok {
		_spec.SetField(bids.FieldMaxPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxPrice(); ok {
		_spec.AddField(bids.FieldMaxPrice, field.TypeFloat64, value)
	}
	if _u.mutation.MaxPriceCleared() {
		_spec.ClearField(bids.FieldMaxPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CargoValue(); ok {
		_spec.SetField(bids.FieldCargoValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCargoValue(); ok {
		_spec.AddField(bids.FieldCargoValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RequiredDeposit(); ok {
		_spec.SetField(bids.FieldRequiredDeposit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRequiredDeposit(); ok {
		_spec.AddField(bids.FieldRequiredDeposit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DesiredDeposit(); ok {
		_spec.SetField(bids.FieldDesiredDeposit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDesiredDeposit(); ok {
		_spec.AddField(bids.FieldDesiredDeposit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ZoneID(); ok {
		_spec.SetField(bids.FieldZoneID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginLat(); ok {
		_spec.SetField(bids.FieldOriginLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginLat(); ok {
		_spec.AddField(bids.FieldOriginLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginLng(); ok {
		_spec.SetField(bids.FieldOriginLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginLng(); ok {
		_spec.AddField(bids.FieldOriginLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DestinationLat(); ok {
		_spec.SetField(bids.FieldDestinationLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDestinationLat(); ok {
		_spec.AddField(bids.FieldDestinationLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DestinationLng(); ok {
		_spec.SetField(bids.FieldDestinationLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDestinationLng(); ok {
		_spec.AddField(bids.FieldDestinationLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OfferedPrice(); ok {
		_spec.SetField(bids.FieldOfferedPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOfferedPrice(); ok {
		_spec.AddField(bids.FieldOfferedPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OfferedPriceCleared() {
		_spec.ClearField(bids.FieldOfferedPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OfferedAskID(); ok {
		_spec.SetField(bids.FieldOfferedAskID, field.TypeUUID, value)
	}
	if _u.mutation.OfferedAskIDCleared() {
		_spec.ClearField(bids.FieldOfferedAskID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bids.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(bids.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(bids.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(bids.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.MatchesTable,
			Columns: []string{bids.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMatchesIDs(); len(nodes) > 0 && !_u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.MatchesTable,
			Columns: []string{bids.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.MatchesTable,
			Columns: []string{bids.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BidsRequirementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.BidsRequirementsTable,
			Columns: []string{bids.BidsRequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bids_requirements.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBidsRequirementsIDs(); len(nodes) > 0 && !_u.mutation.BidsRequirementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.BidsRequirementsTable,
			Columns: []string{bids.BidsRequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bids_requirements.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BidsRequirementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.BidsRequirementsTable,
			Columns: []string{bids.BidsRequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bids_requirements.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bids.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BidsUpdateOne is the builder for updating a single Bids entity.
type BidsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BidsMutation
}

// SetCreatedBy sets the "created_by" field.
func (_u *BidsUpdateOne) SetCreatedBy(v uuid.UUID) *BidsUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *BidsUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BidsUpdateOne) SetUpdatedAt(v time.Time) *BidsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *BidsUpdateOne) SetUpdatedBy(v uuid.UUID) *BidsUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *BidsUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *BidsUpdateOne) SetIsDeleted(v bool) *BidsUpdateOne {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableIsDeleted(v *bool) *BidsUpdateOne {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BidsUpdateOne) SetDeletedAt(v time.Time) *BidsUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableDeletedAt(v *time.Time) *BidsUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BidsUpdateOne) ClearDeletedAt() *BidsUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetShipperID sets the "shipper_id" field.
func (_u *BidsUpdateOne) SetShipperID(v uuid.UUID) *BidsUpdateOne {
	_u.mutation.SetShipperID(v)
	return _u
}

// SetNillableShipperID sets the "shipper_id" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableShipperID(v *uuid.UUID) *BidsUpdateOne {
	if v != nil {
		_u.SetShipperID(*v)
	}
	return _u
}

// SetShipperPhone sets the "shipper_phone" field.
func (_u *BidsUpdateOne) SetShipperPhone(v string) *BidsUpdateOne {
	_u.mutation.SetShipperPhone(v)
	return _u
}

// SetNillableShipperPhone sets the "shipper_phone" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableShipperPhone(v *string) *BidsUpdateOne {
	if v != nil {
		_u.SetShipperPhone(*v)
	}
	return _u
}

// SetShipperMail sets the "shipper_mail" field.
func (_u *BidsUpdateOne) SetShipperMail(v string) *BidsUpdateOne {
	_u.mutation.SetShipperMail(v)
	return _u
}

// SetNillableShipperMail sets the "shipper_mail" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableShipperMail(v *string) *BidsUpdateOne {
	if v != nil {
		_u.SetShipperMail(*v)
	}
	return _u
}

// SetConsigneeID sets the "consignee_id" field.
func (_u *BidsUpdateOne) SetConsigneeID(v uuid.UUID) *BidsUpdateOne {
	_u.mutation.SetConsigneeID(v)
	return _u
}

// SetNillableConsigneeID sets the "consignee_id" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableConsigneeID(v *uuid.UUID) *BidsUpdateOne {
	if v != nil {
		_u.SetConsigneeID(*v)
	}
	return _u
}

// SetConsigneePhone sets the "consignee_phone" field.
func (_u *BidsUpdateOne) SetConsigneePhone(v string) *BidsUpdateOne {
	_u.mutation.SetConsigneePhone(v)
	return _u
}

// SetNillableConsigneePhone sets the "consignee_phone" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableConsigneePhone(v *string) *BidsUpdateOne {
	if v != nil {
		_u.SetConsigneePhone(*v)
	}
	return _u
}

// SetConsigneeMail sets the "consignee_mail" field.
func (_u *BidsUpdateOne) SetConsigneeMail(v string) *BidsUpdateOne {
	_u.mutation.SetConsigneeMail(v)
	return _u
}

// SetNillableConsigneeMail sets the "consignee_mail" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableConsigneeMail(v *string) *BidsUpdateOne {
	if v != nil {
		_u.SetConsigneeMail(*v)
	}
	return _u
}

// SetVolumeM3 sets the "volume_m3" field.
func (_u *BidsUpdateOne) SetVolumeM3(v float64) *BidsUpdateOne {
	_u.mutation.ResetVolumeM3()
	_u.mutation.SetVolumeM3(v)
	return _u
}

// SetNillableVolumeM3 sets the "volume_m3" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableVolumeM3(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetVolumeM3(*v)
	}
	return _u
}

// AddVolumeM3 adds value to the "volume_m3" field.
func (_u *BidsUpdateOne) AddVolumeM3(v float64) *BidsUpdateOne {
	_u.mutation.AddVolumeM3(v)
	return _u
}

// SetWeightKg sets the "weight_kg" field.
func (_u *BidsUpdateOne) SetWeightKg(v float64) *BidsUpdateOne {
	_u.mutation.ResetWeightKg()
	_u.mutation.SetWeightKg(v)
	return _u
}

// SetNillableWeightKg sets the "weight_kg" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableWeightKg(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetWeightKg(*v)
	}
	return _u
}

// AddWeightKg adds value to the "weight_kg" field.
func (_u *BidsUpdateOne) AddWeightKg(v float64) *BidsUpdateOne {
	_u.mutation.AddWeightKg(v)
	return _u
}

// SetMaxPrice sets the "max_price" field.
func (_u *BidsUpdateOne) SetMaxPrice(v float64) *BidsUpdateOne {
	_u.mutation.ResetMaxPrice()
	_u.mutation.SetMaxPrice(v)
	return _u
}

// SetNillableMaxPrice sets the "max_price" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableMaxPrice(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetMaxPrice(*v)
	}
	return _u
}

// AddMaxPrice adds value to the "max_price" field.
func (_u *BidsUpdateOne) AddMaxPrice(v float64) *BidsUpdateOne {
	_u.mutation.AddMaxPrice(v)
	return _u
}

// ClearMaxPrice clears the value of the "max_price" field.
func (_u *BidsUpdateOne) ClearMaxPrice() *BidsUpdateOne {
	_u.mutation.ClearMaxPrice()
	return _u
}

// SetCargoValue sets the "cargo_value" field.
func (_u *BidsUpdateOne) SetCargoValue(v float64) *BidsUpdateOne {
	_u.mutation.ResetCargoValue()
	_u.mutation.SetCargoValue(v)
	return _u
}

// SetNillableCargoValue sets the "cargo_value" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableCargoValue(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetCargoValue(*v)
	}
	return _u
}

// AddCargoValue adds value to the "cargo_value" field.
func (_u *BidsUpdateOne) AddCargoValue(v float64) *BidsUpdateOne {
	_u.mutation.AddCargoValue(v)
	return _u
}

// SetRequiredDeposit sets the "required_deposit" field.
func (_u *BidsUpdateOne) SetRequiredDeposit(v float64) *BidsUpdateOne {
	_u.mutation.ResetRequiredDeposit()
	_u.mutation.SetRequiredDeposit(v)
	return _u
}

// SetNillableRequiredDeposit sets the "required_deposit" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableRequiredDeposit(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetRequiredDeposit(*v)
	}
	return _u
}

// AddRequiredDeposit adds value to the "required_deposit" field.
func (_u *BidsUpdateOne) AddRequiredDeposit(v float64) *BidsUpdateOne {
	_u.mutation.AddRequiredDeposit(v)
	return _u
}

// SetDesiredDeposit sets the "desired_deposit" field.
func (_u *BidsUpdateOne) SetDesiredDeposit(v float64) *BidsUpdateOne {
	_u.mutation.ResetDesiredDeposit()
	_u.mutation.SetDesiredDeposit(v)
	return _u
}

// SetNillableDesiredDeposit sets the "desired_deposit" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableDesiredDeposit(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetDesiredDeposit(*v)
	}
	return _u
}

// AddDesiredDeposit adds value to the "desired_deposit" field.
func (_u *BidsUpdateOne) AddDesiredDeposit(v float64) *BidsUpdateOne {
	_u.mutation.AddDesiredDeposit(v)
	return _u
}

// SetZoneID sets the "zone_id" field.
func (_u *BidsUpdateOne) SetZoneID(v string) *BidsUpdateOne {
	_u.mutation.SetZoneID(v)
	return _u
}

// SetNillableZoneID sets the "zone_id" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableZoneID(v *string) *BidsUpdateOne {
	if v != nil {
		_u.SetZoneID(*v)
	}
	return _u
}

// SetOriginLat sets the "origin_lat" field.
func (_u *BidsUpdateOne) SetOriginLat(v float64) *BidsUpdateOne {
	_u.mutation.ResetOriginLat()
	_u.mutation.SetOriginLat(v)
	return _u
}

// SetNillableOriginLat sets the "origin_lat" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableOriginLat(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetOriginLat(*v)
	}
	return _u
}

// AddOriginLat adds value to the "origin_lat" field.
func (_u *BidsUpdateOne) AddOriginLat(v float64) *BidsUpdateOne {
	_u.mutation.AddOriginLat(v)
	return _u
}

// SetOriginLng sets the "origin_lng" field.
func (_u *BidsUpdateOne) SetOriginLng(v float64) *BidsUpdateOne {
	_u.mutation.ResetOriginLng()
	_u.mutation.SetOriginLng(v)
	return _u
}

// SetNillableOriginLng sets the "origin_lng" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableOriginLng(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetOriginLng(*v)
	}
	return _u
}

// AddOriginLng adds value to the "origin_lng" field.
func (_u *BidsUpdateOne) AddOriginLng(v float64) *BidsUpdateOne {
	_u.mutation.AddOriginLng(v)
	return _u
}

// SetDestinationLat sets the "destination_lat" field.
func (_u *BidsUpdateOne) SetDestinationLat(v float64) *BidsUpdateOne {
	_u.mutation.ResetDestinationLat()
	_u.mutation.SetDestinationLat(v)
	return _u
}

// SetNillableDestinationLat sets the "destination_lat" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableDestinationLat(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetDestinationLat(*v)
	}
	return _u
}

// AddDestinationLat adds value to the "destination_lat" field.
func (_u *BidsUpdateOne) AddDestinationLat(v float64) *BidsUpdateOne {
	_u.mutation.AddDestinationLat(v)
	return _u
}

// SetDestinationLng sets the "destination_lng" field.
func (_u *BidsUpdateOne) SetDestinationLng(v float64) *BidsUpdateOne {
	_u.mutation.ResetDestinationLng()
	_u.mutation.SetDestinationLng(v)
	return _u
}

// SetNillableDestinationLng sets the "destination_lng" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableDestinationLng(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetDestinationLng(*v)
	}
	return _u
}

// AddDestinationLng adds value to the "destination_lng" field.
func (_u *BidsUpdateOne) AddDestinationLng(v float64) *BidsUpdateOne {
	_u.mutation.AddDestinationLng(v)
	return _u
}

// SetOfferedPrice sets the "offered_price" field.
func (_u *BidsUpdateOne) SetOfferedPrice(v float64) *BidsUpdateOne {
	_u.mutation.ResetOfferedPrice()
	_u.mutation.SetOfferedPrice(v)
	return _u
}

// SetNillableOfferedPrice sets the "offered_price" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableOfferedPrice(v *float64) *BidsUpdateOne {
	if v != nil {
		_u.SetOfferedPrice(*v)
	}
	return _u
}

// AddOfferedPrice adds value to the "offered_price" field.
func (_u *BidsUpdateOne) AddOfferedPrice(v float64) *BidsUpdateOne {
	_u.mutation.AddOfferedPrice(v)
	return _u
}

// ClearOfferedPrice clears the value of the "offered_price" field.
func (_u *BidsUpdateOne) ClearOfferedPrice() *BidsUpdateOne {
	_u.mutation.ClearOfferedPrice()
	return _u
}

// SetOfferedAskID sets the "offered_ask_id" field.
func (_u *BidsUpdateOne) SetOfferedAskID(v uuid.UUID) *BidsUpdateOne {
	_u.mutation.SetOfferedAskID(v)
	return _u
}

// SetNillableOfferedAskID sets the "offered_ask_id" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableOfferedAskID(v *uuid.UUID) *BidsUpdateOne {
	if v != nil {
		_u.SetOfferedAskID(*v)
	}
	return _u
}

// ClearOfferedAskID clears the value of the "offered_ask_id" field.
func (_u *BidsUpdateOne) ClearOfferedAskID() *BidsUpdateOne {
	_u.mutation.ClearOfferedAskID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BidsUpdateOne) SetStatus(v int8) *BidsUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableStatus(v *int8) *BidsUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *BidsUpdateOne) AddStatus(v int8) *BidsUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BidsUpdateOne) SetExpiresAt(v time.Time) *BidsUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BidsUpdateOne) SetNillableExpiresAt(v *time.Time) *BidsUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *BidsUpdateOne) ClearExpiresAt() *BidsUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// AddMatchIDs adds the "matches" edge to the Match entity by IDs.
func (_u *BidsUpdateOne) AddMatchIDs(ids ...uuid.UUID) *BidsUpdateOne {
	_u.mutation.AddMatchIDs(ids...)
	return _u
}

// AddMatches adds the "matches" edges to the Match entity.
func (_u *BidsUpdateOne) AddMatches(v ...*Match) *BidsUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMatchIDs(ids...)
}

// AddBidsRequirementIDs adds the "bids_requirements" edge to the Bids_Requirements entity by IDs.
func (_u *BidsUpdateOne) AddBidsRequirementIDs(ids ...uuid.UUID) *BidsUpdateOne {
	_u.mutation.AddBidsRequirementIDs(ids...)
	return _u
}

// AddBidsRequirements adds the "bids_requirements" edges to the Bids_Requirements entity.
func (_u *BidsUpdateOne) AddBidsRequirements(v ...*Bids_Requirements) *BidsUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBidsRequirementIDs(ids...)
}

// Mutation returns the BidsMutation object of the builder.
func (_u *BidsUpdateOne) Mutation() *BidsMutation {
	return _u.mutation
}

// ClearMatches clears all "matches" edges to the Match entity.
func (_u *BidsUpdateOne) ClearMatches() *BidsUpdateOne {
	_u.mutation.ClearMatches()
	return _u
}

// RemoveMatchIDs removes the "matches" edge to Match entities by IDs.
func (_u *BidsUpdateOne) RemoveMatchIDs(ids ...uuid.UUID) *BidsUpdateOne {
	_u.mutation.RemoveMatchIDs(ids...)
	return _u
}

// RemoveMatches removes "matches" edges to Match entities.
func (_u *BidsUpdateOne) RemoveMatches(v ...*Match) *BidsUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMatchIDs(ids...)
}

// ClearBidsRequirements clears all "bids_requirements" edges to the Bids_Requirements entity.
func (_u *BidsUpdateOne) ClearBidsRequirements() *BidsUpdateOne {
	_u.mutation.ClearBidsRequirements()
	return _u
}

// RemoveBidsRequirementIDs removes the "bids_requirements" edge to Bids_Requirements entities by IDs.
func (_u *BidsUpdateOne) RemoveBidsRequirementIDs(ids ...uuid.UUID) *BidsUpdateOne {
	_u.mutation.RemoveBidsRequirementIDs(ids...)
	return _u
}

// RemoveBidsRequirements removes "bids_requirements" edges to Bids_Requirements entities.
func (_u *BidsUpdateOne) RemoveBidsRequirements(v ...*Bids_Requirements) *BidsUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBidsRequirementIDs(ids...)
}

// Where appends a list predicates to the BidsUpdate builder.
func (_u *BidsUpdateOne) Where(ps ...predicate.Bids) *BidsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BidsUpdateOne) Select(field string, fields ...string) *BidsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Bids entity.
func (_u *BidsUpdateOne) Save(ctx context.Context) (*Bids, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BidsUpdateOne) SaveX(ctx context.Context) *Bids {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BidsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BidsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BidsUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if bids.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized bids.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := bids.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *BidsUpdateOne) sqlSave(ctx context.Context) (_node *Bids, err error) {
	_spec := sqlgraph.NewUpdateSpec(bids.Table, bids.Columns, sqlgraph.NewFieldSpec(bids.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Bids.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bids.FieldID)
		for _, f := range fields {
			if !bids.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bids.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(bids.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bids.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(bids.FieldUpdatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(bids.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(bids.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(bids.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ShipperID(); ok {
		_spec.SetField(bids.FieldShipperID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ShipperPhone(); ok {
		_spec.SetField(bids.FieldShipperPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShipperMail(); ok {
		_spec.SetField(bids.FieldShipperMail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsigneeID(); ok {
		_spec.SetField(bids.FieldConsigneeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ConsigneePhone(); ok {
		_spec.SetField(bids.FieldConsigneePhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsigneeMail(); ok {
		_spec.SetField(bids.FieldConsigneeMail, field.TypeString, value)
	}
	if value, ok := _u.mutation.VolumeM3(); ok {
		_spec.SetField(bids.FieldVolumeM3, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedVolumeM3(); ok {
		_spec.AddField(bids.FieldVolumeM3, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeightKg(); ok {
		_spec.SetField(bids.FieldWeightKg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeightKg(); ok {
		_spec.AddField(bids.FieldWeightKg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxPrice(); ok {
		_spec.SetField(bids.FieldMaxPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxPrice(); ok {
		_spec.AddField(bids.FieldMaxPrice, field.TypeFloat64, value)
	}
	if _u.mutation.MaxPriceCleared() {
		_spec.ClearField(bids.FieldMaxPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CargoValue(); ok {
		_spec.SetField(bids.FieldCargoValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCargoValue(); ok {
		_spec.AddField(bids.FieldCargoValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RequiredDeposit(); ok {
		_spec.SetField(bids.FieldRequiredDeposit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRequiredDeposit(); ok {
		_spec.AddField(bids.FieldRequiredDeposit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DesiredDeposit(); ok {
		_spec.SetField(bids.FieldDesiredDeposit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDesiredDeposit(); ok {
		_spec.AddField(bids.FieldDesiredDeposit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ZoneID(); ok {
		_spec.SetField(bids.FieldZoneID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginLat(); ok {
		_spec.SetField(bids.FieldOriginLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginLat(); ok {
		_spec.AddField(bids.FieldOriginLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginLng(); ok {
		_spec.SetField(bids.FieldOriginLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginLng(); ok {
		_spec.AddField(bids.FieldOriginLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DestinationLat(); ok {
		_spec.SetField(bids.FieldDestinationLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDestinationLat(); ok {
		_spec.AddField(bids.FieldDestinationLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DestinationLng(); ok {
		_spec.SetField(bids.FieldDestinationLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDestinationLng(); ok {
		_spec.AddField(bids.FieldDestinationLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OfferedPrice(); ok {
		_spec.SetField(bids.FieldOfferedPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOfferedPrice(); ok {
		_spec.AddField(bids.FieldOfferedPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OfferedPriceCleared() {
		_spec.ClearField(bids.FieldOfferedPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OfferedAskID(); ok {
		_spec.SetField(bids.FieldOfferedAskID, field.TypeUUID, value)
	}
	if _u.mutation.OfferedAskIDCleared() {
		_spec.ClearField(bids.FieldOfferedAskID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bids.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(bids.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(bids.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(bids.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.MatchesTable,
			Columns: []string{bids.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMatchesIDs(); len(nodes) > 0 && !_u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.MatchesTable,
			Columns: []string{bids.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.MatchesTable,
			Columns: []string{bids.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(match.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BidsRequirementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.BidsRequirementsTable,
			Columns: []string{bids.BidsRequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bids_requirements.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBidsRequirementsIDs(); len(nodes) > 0 && !_u.mutation.BidsRequirementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.BidsRequirementsTable,
			Columns: []string{bids.BidsRequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bids_requirements.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BidsRequirementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bids.BidsRequirementsTable,
			Columns: []string{bids.BidsRequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bids_requirements.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Bids{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bids.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
