// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"matching_service/ent/asks"
	"matching_service/ent/bids"
	"matching_service/ent/match"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Match is the model entity for the Match schema.
type Match struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy uuid.UUID `json:"updated_by,omitempty"`
	// IsDeleted holds the value of the "is_deleted" field.
	IsDeleted bool `json:"is_deleted,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// Logical FK point to Bids
	BidID uuid.UUID `json:"bid_id,omitempty"`
	// Logical FK point to Asks
	AskID uuid.UUID `json:"ask_id,omitempty"`
	// AgreedPrice holds the value of the "agreed_price" field.
	AgreedPrice float64 `json:"agreed_price,omitempty"`
	// Status holds the value of the "status" field.
	Status int `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MatchQuery when eager-loading is set.
	Edges        MatchEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MatchEdges holds the relations/edges for other nodes in the graph.
type MatchEdges struct {
	// Asks holds the value of the asks edge.
	Asks *Asks `json:"asks,omitempty"`
	// Bids holds the value of the bids edge.
	Bids *Bids `json:"bids,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AsksOrErr returns the Asks value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MatchEdges) AsksOrErr() (*Asks, error) {
	if e.Asks != nil {
		return e.Asks, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: asks.Label}
	}
	return nil, &NotLoadedError{edge: "asks"}
}

// BidsOrErr returns the Bids value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MatchEdges) BidsOrErr() (*Bids, error) {
	if e.Bids != nil {
		return e.Bids, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: bids.Label}
	}
	return nil, &NotLoadedError{edge: "bids"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Match) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case match.FieldIsDeleted:
			values[i] = new(sql.NullBool)
		case match.FieldAgreedPrice:
			values[i] = new(sql.NullFloat64)
		case match.FieldID, match.FieldStatus:
			values[i] = new(sql.NullInt64)
		case match.FieldCreatedAt, match.FieldUpdatedAt, match.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case match.FieldCreatedBy, match.FieldUpdatedBy, match.FieldBidID, match.FieldAskID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Match fields.
func (_m *Match) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case match.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case match.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case match.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case match.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case match.FieldUpdatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value != nil {
				_m.UpdatedBy = *value
			}
		case match.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				_m.IsDeleted = value.Bool
			}
		case match.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case match.FieldBidID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field bid_id", values[i])
			} else if value != nil {
				_m.BidID = *value
			}
		case match.FieldAskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field ask_id", values[i])
			} else if value != nil {
				_m.AskID = *value
			}
		case match.FieldAgreedPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field agreed_price", values[i])
			} else if value.Valid {
				_m.AgreedPrice = value.Float64
			}
		case match.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Match.
// This includes values selected through modifiers, order, etc.
func (_m *Match) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAsks queries the "asks" edge of the Match entity.
func (_m *Match) QueryAsks() *AsksQuery {
	return NewMatchClient(_m.config).QueryAsks(_m)
}

// QueryBids queries the "bids" edge of the Match entity.
func (_m *Match) QueryBids() *BidsQuery {
	return NewMatchClient(_m.config).QueryBids(_m)
}

// Update returns a builder for updating this Match.
// Note that you need to call Match.Unwrap() before calling this method if this Match
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Match) Update() *MatchUpdateOne {
	return NewMatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Match entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Match) Unwrap() *Match {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Match is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Match) String() string {
	var builder strings.Builder
	builder.WriteString("Match(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDeleted))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("bid_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BidID))
	builder.WriteString(", ")
	builder.WriteString("ask_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AskID))
	builder.WriteString(", ")
	builder.WriteString("agreed_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgreedPrice))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// Matches is a parsable slice of Match.
type Matches []*Match
