// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: logistic/user_service/v1/user_messages.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_logistic_user_service_v1_user_messages_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DriverProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,2,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	IdCard        string                 `protobuf:"bytes,3,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Rating        float32                `protobuf:"fixed32,4,opt,name=rating,proto3" json:"rating,omitempty"`
	KycStatus     string                 `protobuf:"bytes,5,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverProfile) Reset() {
	*x = DriverProfile{}
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverProfile) ProtoMessage() {}

func (x *DriverProfile) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverProfile.ProtoReflect.Descriptor instead.
func (*DriverProfile) Descriptor() ([]byte, []int) {
	return file_logistic_user_service_v1_user_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DriverProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DriverProfile) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *DriverProfile) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *DriverProfile) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *DriverProfile) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

type ShipperProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyName   string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	TaxCode       string                 `protobuf:"bytes,3,opt,name=tax_code,json=taxCode,proto3" json:"tax_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipperProfile) Reset() {
	*x = ShipperProfile{}
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipperProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipperProfile) ProtoMessage() {}

func (x *ShipperProfile) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipperProfile.ProtoReflect.Descriptor instead.
func (*ShipperProfile) Descriptor() ([]byte, []int) {
	return file_logistic_user_service_v1_user_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ShipperProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShipperProfile) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *ShipperProfile) GetTaxCode() string {
	if x != nil {
		return x.TaxCode
	}
	return ""
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // "driver" or "shipper"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_logistic_user_service_v1_user_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_logistic_user_service_v1_user_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_logistic_user_service_v1_user_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	User           *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	DriverProfile  *DriverProfile         `protobuf:"bytes,2,opt,name=driver_profile,json=driverProfile,proto3" json:"driver_profile,omitempty"`    // only if role == driver
	ShipperProfile *ShipperProfile        `protobuf:"bytes,3,opt,name=shipper_profile,json=shipperProfile,proto3" json:"shipper_profile,omitempty"` // only if role == shipper
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_logistic_user_service_v1_user_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResponse) GetDriverProfile() *DriverProfile {
	if x != nil {
		return x.DriverProfile
	}
	return nil
}

func (x *GetUserResponse) GetShipperProfile() *ShipperProfile {
	if x != nil {
		return x.ShipperProfile
	}
	return nil
}

type UpdateDriverKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KycStatus     string                 `protobuf:"bytes,2,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"` // "approved" or "rejected"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverKYCRequest) Reset() {
	*x = UpdateDriverKYCRequest{}
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverKYCRequest) ProtoMessage() {}

func (x *UpdateDriverKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverKYCRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverKYCRequest) Descriptor() ([]byte, []int) {
	return file_logistic_user_service_v1_user_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDriverKYCRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateDriverKYCRequest) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

type UpdateDriverKYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverKYCResponse) Reset() {
	*x = UpdateDriverKYCResponse{}
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverKYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverKYCResponse) ProtoMessage() {}

func (x *UpdateDriverKYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logistic_user_service_v1_user_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverKYCResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverKYCResponse) Descriptor() ([]byte, []int) {
	return file_logistic_user_service_v1_user_messages_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDriverKYCResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_logistic_user_service_v1_user_messages_proto protoreflect.FileDescriptor

const file_logistic_user_service_v1_user_messages_proto_rawDesc = "" +
	"\n" +
	",logistic/user_service/v1/user_messages.proto\x12\x18logistic.user_service.v1\"\xac\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\x9f\x01\n" +
	"\rDriverProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0elicense_number\x18\x02 \x01(\tR\rlicenseNumber\x12\x17\n" +
	"\aid_card\x18\x03 \x01(\tR\x06idCard\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x02R\x06rating\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\x05 \x01(\tR\tkycStatus\"g\n" +
	"\x0eShipperProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12\x19\n" +
	"\btax_code\x18\x03 \x01(\tR\ataxCode\"q\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"@\n" +
	"\x14RegisterUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe8\x01\n" +
	"\x0fGetUserResponse\x122\n" +
	"\x04user\x18\x01 \x01(\v2\x1e.logistic.user_service.v1.UserR\x04user\x12N\n" +
	"\x0edriver_profile\x18\x02 \x01(\v2'.logistic.user_service.v1.DriverProfileR\rdriverProfile\x12Q\n" +
	"\x0fshipper_profile\x18\x03 \x01(\v2(.logistic.user_service.v1.ShipperProfileR\x0eshipperProfile\"P\n" +
	"\x16UpdateDriverKYCRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\x02 \x01(\tR\tkycStatus\"3\n" +
	"\x17UpdateDriverKYCResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB9Z7github.com/logistic/api/logistic/user_service/v1;userv1b\x06proto3"

var (
	file_logistic_user_service_v1_user_messages_proto_rawDescOnce sync.Once
	file_logistic_user_service_v1_user_messages_proto_rawDescData []byte
)

func file_logistic_user_service_v1_user_messages_proto_rawDescGZIP() []byte {
	file_logistic_user_service_v1_user_messages_proto_rawDescOnce.Do(func() {
		file_logistic_user_service_v1_user_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logistic_user_service_v1_user_messages_proto_rawDesc), len(file_logistic_user_service_v1_user_messages_proto_rawDesc)))
	})
	return file_logistic_user_service_v1_user_messages_proto_rawDescData
}

var file_logistic_user_service_v1_user_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_logistic_user_service_v1_user_messages_proto_goTypes = []any{
	(*User)(nil),                    // 0: logistic.user_service.v1.User
	(*DriverProfile)(nil),           // 1: logistic.user_service.v1.DriverProfile
	(*ShipperProfile)(nil),          // 2: logistic.user_service.v1.ShipperProfile
	(*RegisterUserRequest)(nil),     // 3: logistic.user_service.v1.RegisterUserRequest
	(*RegisterUserResponse)(nil),    // 4: logistic.user_service.v1.RegisterUserResponse
	(*GetUserRequest)(nil),          // 5: logistic.user_service.v1.GetUserRequest
	(*GetUserResponse)(nil),         // 6: logistic.user_service.v1.GetUserResponse
	(*UpdateDriverKYCRequest)(nil),  // 7: logistic.user_service.v1.UpdateDriverKYCRequest
	(*UpdateDriverKYCResponse)(nil), // 8: logistic.user_service.v1.UpdateDriverKYCResponse
}
var file_logistic_user_service_v1_user_messages_proto_depIdxs = []int32{
	0, // 0: logistic.user_service.v1.GetUserResponse.user:type_name -> logistic.user_service.v1.User
	1, // 1: logistic.user_service.v1.GetUserResponse.driver_profile:type_name -> logistic.user_service.v1.DriverProfile
	2, // 2: logistic.user_service.v1.GetUserResponse.shipper_profile:type_name -> logistic.user_service.v1.ShipperProfile
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_logistic_user_service_v1_user_messages_proto_init() }
func file_logistic_user_service_v1_user_messages_proto_init() {
	if File_logistic_user_service_v1_user_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logistic_user_service_v1_user_messages_proto_rawDesc), len(file_logistic_user_service_v1_user_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logistic_user_service_v1_user_messages_proto_goTypes,
		DependencyIndexes: file_logistic_user_service_v1_user_messages_proto_depIdxs,
		MessageInfos:      file_logistic_user_service_v1_user_messages_proto_msgTypes,
	}.Build()
	File_logistic_user_service_v1_user_messages_proto = out.File
	file_logistic_user_service_v1_user_messages_proto_goTypes = nil
	file_logistic_user_service_v1_user_messages_proto_depIdxs = nil
}
