// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: logistic/matching_service/v1/matching_service.proto

package matchingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_logistic_matching_service_v1_matching_service_proto protoreflect.FileDescriptor

const file_logistic_matching_service_v1_matching_service_proto_rawDesc = "" +
	"\n" +
	"3logistic/matching_service/v1/matching_service.proto\x12\x1clogistic.matching_service.v1\x1a4logistic/matching_service/v1/matching_messages.proto2\xcf\x04\n" +
	"\x15MatchingEngineService\x12l\n" +
	"\tSubmitBid\x12..logistic.matching_service.v1.SubmitBidRequest\x1a/.logistic.matching_service.v1.SubmitBidResponse\x12l\n" +
	"\tSubmitAsk\x12..logistic.matching_service.v1.SubmitAskRequest\x1a/.logistic.matching_service.v1.SubmitAskResponse\x12r\n" +
	"\vAcceptMatch\x120.logistic.matching_service.v1.AcceptMatchRequest\x1a1.logistic.matching_service.v1.AcceptMatchResponse\x12r\n" +
	"\vSubmitOffer\x120.logistic.matching_service.v1.SubmitOfferRequest\x1a1.logistic.matching_service.v1.SubmitOfferResponse\x12r\n" +
	"\vRejectOffer\x120.logistic.matching_service.v1.RejectOfferRequest\x1a1.logistic.matching_service.v1.RejectOfferResponseBAZ?github.com/logistic/api/logistic/matching_service/v1;matchingv1b\x06proto3"

var file_logistic_matching_service_v1_matching_service_proto_goTypes = []any{
	(*SubmitBidRequest)(nil),    // 0: logistic.matching_service.v1.SubmitBidRequest
	(*SubmitAskRequest)(nil),    // 1: logistic.matching_service.v1.SubmitAskRequest
	(*AcceptMatchRequest)(nil),  // 2: logistic.matching_service.v1.AcceptMatchRequest
	(*SubmitOfferRequest)(nil),  // 3: logistic.matching_service.v1.SubmitOfferRequest
	(*RejectOfferRequest)(nil),  // 4: logistic.matching_service.v1.RejectOfferRequest
	(*SubmitBidResponse)(nil),   // 5: logistic.matching_service.v1.SubmitBidResponse
	(*SubmitAskResponse)(nil),   // 6: logistic.matching_service.v1.SubmitAskResponse
	(*AcceptMatchResponse)(nil), // 7: logistic.matching_service.v1.AcceptMatchResponse
	(*SubmitOfferResponse)(nil), // 8: logistic.matching_service.v1.SubmitOfferResponse
	(*RejectOfferResponse)(nil), // 9: logistic.matching_service.v1.RejectOfferResponse
}
var file_logistic_matching_service_v1_matching_service_proto_depIdxs = []int32{
	0, // 0: logistic.matching_service.v1.MatchingEngineService.SubmitBid:input_type -> logistic.matching_service.v1.SubmitBidRequest
	1, // 1: logistic.matching_service.v1.MatchingEngineService.SubmitAsk:input_type -> logistic.matching_service.v1.SubmitAskRequest
	2, // 2: logistic.matching_service.v1.MatchingEngineService.AcceptMatch:input_type -> logistic.matching_service.v1.AcceptMatchRequest
	3, // 3: logistic.matching_service.v1.MatchingEngineService.SubmitOffer:input_type -> logistic.matching_service.v1.SubmitOfferRequest
	4, // 4: logistic.matching_service.v1.MatchingEngineService.RejectOffer:input_type -> logistic.matching_service.v1.RejectOfferRequest
	5, // 5: logistic.matching_service.v1.MatchingEngineService.SubmitBid:output_type -> logistic.matching_service.v1.SubmitBidResponse
	6, // 6: logistic.matching_service.v1.MatchingEngineService.SubmitAsk:output_type -> logistic.matching_service.v1.SubmitAskResponse
	7, // 7: logistic.matching_service.v1.MatchingEngineService.AcceptMatch:output_type -> logistic.matching_service.v1.AcceptMatchResponse
	8, // 8: logistic.matching_service.v1.MatchingEngineService.SubmitOffer:output_type -> logistic.matching_service.v1.SubmitOfferResponse
	9, // 9: logistic.matching_service.v1.MatchingEngineService.RejectOffer:output_type -> logistic.matching_service.v1.RejectOfferResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logistic_matching_service_v1_matching_service_proto_init() }
func file_logistic_matching_service_v1_matching_service_proto_init() {
	if File_logistic_matching_service_v1_matching_service_proto != nil {
		return
	}
	file_logistic_matching_service_v1_matching_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logistic_matching_service_v1_matching_service_proto_rawDesc), len(file_logistic_matching_service_v1_matching_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logistic_matching_service_v1_matching_service_proto_goTypes,
		DependencyIndexes: file_logistic_matching_service_v1_matching_service_proto_depIdxs,
	}.Build()
	File_logistic_matching_service_v1_matching_service_proto = out.File
	file_logistic_matching_service_v1_matching_service_proto_goTypes = nil
	file_logistic_matching_service_v1_matching_service_proto_depIdxs = nil
}
