syntax = "proto3";

package logistic.matching_service.v1;

import "google/protobuf/timestamp.proto";

option go_package = "logistic_project/api/logistic/matching/v1";

// Location represents a geographic point and a logical zone for simplified matching
message Location {
  double latitude = 1;
  double longitude = 2;
  // zone_id is used for quick in-memory spatial partitioning (e.g., "VN-HCM-Q1")
  string zone_id = 3;
}

// SubmitBidRequest represents the demand side (Cargo)
message SubmitBidRequest {
  string trace_id = 1;
  string session_id = 2;
  bytes requested_by = 3;
  google.protobuf.Timestamp requested_at = 4;
  Bid payload = 5;
}

message SubmitBidResponse {
  bytes bid_id = 1;
  string status = 2; // e.g., "PENDING", "MATCHED", "EXPIRED"
}

// SubmitAskRequest represents the supply side (Empty Vehicle)
message SubmitAskRequest {
  string trace_id = 1;
  string session_id = 2;
  bytes requested_by = 3;
  google.protobuf.Timestamp requested_at = 4;
  Ask payload = 5;
}

message SubmitAskResponse {
  bytes ask_id = 1;
  string status = 2; // e.g., "PENDING", "MATCHED", "EXPIRED"
}

// Domain Models for Event Publishing
message Bid {
  bytes id = 1;

  bytes shipper_id = 2;
  string shipper_phone = 3;
  string shipper_mail = 4;

  bytes consignee_id = 5;
  string consignee_phone = 6;
  string consignee_mail = 7;

  Location origin = 8;
  Location destination = 9;

  double volume_m3 = 10;
  double weight_kg = 11;

  double max_price = 12;

  int32 status = 13;

  double cargo_value = 14;
  double required_deposit = 15;
  double desired_deposit = 16;

  google.protobuf.Timestamp expires_at = 18;
  google.protobuf.Timestamp created_at = 19;
}

message Bids {
  repeated Bid bids = 1;
}

message Ask {
  bytes id = 1;

  bytes driver_id = 2;
  string driver_phone = 3;
  string driver_mail = 4;

  bytes vehicle_id = 5;

  Location current_location = 6;
  Location destination = 7;

  double available_volume_m3 = 8;
  double available_weight_kg = 9;

  double min_price = 10;

  int32 status = 11;

  double desired_deposit = 12;

  google.protobuf.Timestamp expires_at = 13;
  google.protobuf.Timestamp created_at = 14;
}

message Asks {
  repeated Ask asks = 1;
}

message AcceptMatchRequest {
  bytes id = 1;

  bytes bid_id = 2;
  bytes ask_id = 3;
  bytes shipper_id = 4;
  bytes driver_id = 5;

  double consensus_price = 6;
  double consensus_deposit = 7;

  string shipper_signature = 8;
  google.protobuf.Timestamp agreed_at = 9;
}

message AcceptMatchResponse {
  bytes contract_id = 1;
  bytes bid_id = 2;
  bytes ask_id = 3;

  double consensus_price = 4;
  double consensus_deposit = 5;

  string shipper_signature = 6;
  string driver_signature = 7;
  string system_signature = 8;

  google.protobuf.Timestamp agreed_at = 9;
  google.protobuf.Timestamp created_at = 10;
}
