// Code generated by ent, DO NOT EDIT.

package driverprofile

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the driverprofile type in the database.
	Label = "driver_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldLicenseNumber holds the string denoting the license_number field in the database.
	FieldLicenseNumber = "license_number"
	// FieldIDCard holds the string denoting the id_card field in the database.
	FieldIDCard = "id_card"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldTotalTrips holds the string denoting the total_trips field in the database.
	FieldTotalTrips = "total_trips"
	// FieldKycStatus holds the string denoting the kyc_status field in the database.
	FieldKycStatus = "kyc_status"
	// FieldKycNote holds the string denoting the kyc_note field in the database.
	FieldKycNote = "kyc_note"
	// FieldKycReviewedBy holds the string denoting the kyc_reviewed_by field in the database.
	FieldKycReviewedBy = "kyc_reviewed_by"
	// FieldKycReviewedAt holds the string denoting the kyc_reviewed_at field in the database.
	FieldKycReviewedAt = "kyc_reviewed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the driverprofile in the database.
	Table = "driver_profiles"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "driver_profiles"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for driverprofile fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldLicenseNumber,
	FieldIDCard,
	FieldRating,
	FieldTotalTrips,
	FieldKycStatus,
	FieldKycNote,
	FieldKycReviewedBy,
	FieldKycReviewedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRating holds the default value on creation for the "rating" field.
	DefaultRating float64
	// DefaultTotalTrips holds the default value on creation for the "total_trips" field.
	DefaultTotalTrips int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// KycStatus defines the type for the "kyc_status" enum field.
type KycStatus string

// KycStatusPending is the default value of the KycStatus enum.
const DefaultKycStatus = KycStatusPending

// KycStatus values.
const (
	KycStatusPending  KycStatus = "pending"
	KycStatusApproved KycStatus = "approved"
	KycStatusRejected KycStatus = "rejected"
)

func (ks KycStatus) String() string {
	return string(ks)
}

// KycStatusValidator is a validator for the "kyc_status" field enum values. It is called by the builders before save.
func KycStatusValidator(ks KycStatus) error {
	switch ks {
	case KycStatusPending, KycStatusApproved, KycStatusRejected:
		return nil
	default:
		return fmt.Errorf("driverprofile: invalid enum value for kyc_status field: %q", ks)
	}
}

// OrderOption defines the ordering options for the DriverProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByLicenseNumber orders the results by the license_number field.
func ByLicenseNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicenseNumber, opts...).ToFunc()
}

// ByIDCard orders the results by the id_card field.
func ByIDCard(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIDCard, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByTotalTrips orders the results by the total_trips field.
func ByTotalTrips(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTrips, opts...).ToFunc()
}

// ByKycStatus orders the results by the kyc_status field.
func ByKycStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKycStatus, opts...).ToFunc()
}

// ByKycNote orders the results by the kyc_note field.
func ByKycNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKycNote, opts...).ToFunc()
}

// ByKycReviewedBy orders the results by the kyc_reviewed_by field.
func ByKycReviewedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKycReviewedBy, opts...).ToFunc()
}

// ByKycReviewedAt orders the results by the kyc_reviewed_at field.
func ByKycReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKycReviewedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
