// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wallet_service/ent/processedmessage"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProcessedMessageCreate is the builder for creating a ProcessedMessage entity.
type ProcessedMessageCreate struct {
	config
	mutation *ProcessedMessageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProcessedMessageCreate) SetCreatedAt(v time.Time) *ProcessedMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProcessedMessageCreate) SetNillableCreatedAt(v *time.Time) *ProcessedMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ProcessedMessageCreate) SetCreatedBy(v uuid.UUID) *ProcessedMessageCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ProcessedMessageCreate) SetNillableCreatedBy(v *uuid.UUID) *ProcessedMessageCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProcessedMessageCreate) SetUpdatedAt(v time.Time) *ProcessedMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProcessedMessageCreate) SetNillableUpdatedAt(v *time.Time) *ProcessedMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ProcessedMessageCreate) SetUpdatedBy(v uuid.UUID) *ProcessedMessageCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ProcessedMessageCreate) SetNillableUpdatedBy(v *uuid.UUID) *ProcessedMessageCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetIsDeleted sets the "is_deleted" field.
func (_c *ProcessedMessageCreate) SetIsDeleted(v bool) *ProcessedMessageCreate {
	_c.mutation.SetIsDeleted(v)
	return _c
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_c *ProcessedMessageCreate) SetNillableIsDeleted(v *bool) *ProcessedMessageCreate {
	if v != nil {
		_c.SetIsDeleted(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProcessedMessageCreate) SetID(v string) *ProcessedMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProcessedMessageMutation object of the builder.
func (_c *ProcessedMessageCreate) Mutation() *ProcessedMessageMutation {
	return _c.mutation
}

// Save creates the ProcessedMessage in the database.
func (_c *ProcessedMessageCreate) Save(ctx context.Context) (*ProcessedMessage, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProcessedMessageCreate) SaveX(ctx context.Context) *ProcessedMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessedMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessedMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProcessedMessageCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if processedmessage.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized processedmessage.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := processedmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		if processedmessage.DefaultCreatedBy == nil {
			return fmt.Errorf("ent: uninitialized processedmessage.DefaultCreatedBy (forgotten import ent/runtime?)")
		}
		v := processedmessage.DefaultCreatedBy()
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if processedmessage.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized processedmessage.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := processedmessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		if processedmessage.DefaultUpdatedBy == nil {
			return fmt.Errorf("ent: uninitialized processedmessage.DefaultUpdatedBy (forgotten import ent/runtime?)")
		}
		v := processedmessage.DefaultUpdatedBy()
		_c.mutation.SetUpdatedBy(v)
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		v := processedmessage.DefaultIsDeleted
		_c.mutation.SetIsDeleted(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProcessedMessageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProcessedMessage.created_at"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ProcessedMessage.created_by"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProcessedMessage.updated_at"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "ProcessedMessage.updated_by"`)}
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "ProcessedMessage.is_deleted"`)}
	}
	return nil
}

func (_c *ProcessedMessageCreate) sqlSave(ctx context.Context) (*ProcessedMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ProcessedMessage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProcessedMessageCreate) createSpec() (*ProcessedMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ProcessedMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(processedmessage.Table, sqlgraph.NewFieldSpec(processedmessage.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(processedmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(processedmessage.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(processedmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(processedmessage.FieldUpdatedBy, field.TypeUUID, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.IsDeleted(); ok {
		_spec.SetField(processedmessage.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	return _node, _spec
}

// ProcessedMessageCreateBulk is the builder for creating many ProcessedMessage entities in bulk.
type ProcessedMessageCreateBulk struct {
	config
	err      error
	builders []*ProcessedMessageCreate
}

// Save creates the ProcessedMessage entities in the database.
func (_c *ProcessedMessageCreateBulk) Save(ctx context.Context) ([]*ProcessedMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProcessedMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProcessedMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProcessedMessageCreateBulk) SaveX(ctx context.Context) []*ProcessedMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessedMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessedMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
