// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wallet_service/ent/predicate"
	"wallet_service/ent/transaction"
	"wallet_service/ent/wallet"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks     []Hook
	mutation  *TransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TransactionUpdate) SetCreatedBy(v uuid.UUID) *TransactionUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableCreatedBy(v *uuid.UUID) *TransactionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdate) SetUpdatedAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TransactionUpdate) SetUpdatedBy(v uuid.UUID) *TransactionUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableUpdatedBy(v *uuid.UUID) *TransactionUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *TransactionUpdate) SetIsDeleted(v bool) *TransactionUpdate {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableIsDeleted(v *bool) *TransactionUpdate {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TransactionUpdate) SetDeletedAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableDeletedAt(v *time.Time) *TransactionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TransactionUpdate) ClearDeletedAt() *TransactionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWalletID sets the "wallet_id" field.
func (_u *TransactionUpdate) SetWalletID(v uuid.UUID) *TransactionUpdate {
	_u.mutation.SetWalletID(v)
	return _u
}

// SetNillableWalletID sets the "wallet_id" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableWalletID(v *uuid.UUID) *TransactionUpdate {
	if v != nil {
		_u.SetWalletID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdate) SetAmount(v int64) *TransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableAmount(v *int64) *TransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdate) AddAmount(v int64) *TransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetTransactionType sets the "transaction_type" field.
func (_u *TransactionUpdate) SetTransactionType(v uint8) *TransactionUpdate {
	_u.mutation.ResetTransactionType()
	_u.mutation.SetTransactionType(v)
	return _u
}

// SetNillableTransactionType sets the "transaction_type" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableTransactionType(v *uint8) *TransactionUpdate {
	if v != nil {
		_u.SetTransactionType(*v)
	}
	return _u
}

// AddTransactionType adds value to the "transaction_type" field.
func (_u *TransactionUpdate) AddTransactionType(v int8) *TransactionUpdate {
	_u.mutation.AddTransactionType(v)
	return _u
}

// SetReferenceID sets the "reference_id" field.
func (_u *TransactionUpdate) SetReferenceID(v string) *TransactionUpdate {
	_u.mutation.SetReferenceID(v)
	return _u
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableReferenceID(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetReferenceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransactionUpdate) SetStatus(v uint8) *TransactionUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableStatus(v *uint8) *TransactionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TransactionUpdate) AddStatus(v int8) *TransactionUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdate) SetDescription(v string) *TransactionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableDescription(v *string) *TransactionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (_u *TransactionUpdate) SetWallet(v *Wallet) *TransactionUpdate {
	return _u.SetWalletID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdate) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (_u *TransactionUpdate) ClearWallet() *TransactionUpdate {
	_u.mutation.ClearWallet()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if transaction.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized transaction.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdate) check() error {
	if _u.mutation.WalletCleared() && len(_u.mutation.WalletIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Transaction.wallet"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TransactionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransactionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(transaction.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(transaction.FieldUpdatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(transaction.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(transaction.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(transaction.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TransactionType(); ok {
		_spec.SetField(transaction.FieldTransactionType, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedTransactionType(); ok {
		_spec.AddField(transaction.FieldTransactionType, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.ReferenceID(); ok {
		_spec.SetField(transaction.FieldReferenceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transaction.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(transaction.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TransactionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedBy sets the "created_by" field.
func (_u *TransactionUpdateOne) SetCreatedBy(v uuid.UUID) *TransactionUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *TransactionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdateOne) SetUpdatedAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TransactionUpdateOne) SetUpdatedBy(v uuid.UUID) *TransactionUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *TransactionUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *TransactionUpdateOne) SetIsDeleted(v bool) *TransactionUpdateOne {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableIsDeleted(v *bool) *TransactionUpdateOne {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TransactionUpdateOne) SetDeletedAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableDeletedAt(v *time.Time) *TransactionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TransactionUpdateOne) ClearDeletedAt() *TransactionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWalletID sets the "wallet_id" field.
func (_u *TransactionUpdateOne) SetWalletID(v uuid.UUID) *TransactionUpdateOne {
	_u.mutation.SetWalletID(v)
	return _u
}

// SetNillableWalletID sets the "wallet_id" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableWalletID(v *uuid.UUID) *TransactionUpdateOne {
	if v != nil {
		_u.SetWalletID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionUpdateOne) SetAmount(v int64) *TransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableAmount(v *int64) *TransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionUpdateOne) AddAmount(v int64) *TransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetTransactionType sets the "transaction_type" field.
func (_u *TransactionUpdateOne) SetTransactionType(v uint8) *TransactionUpdateOne {
	_u.mutation.ResetTransactionType()
	_u.mutation.SetTransactionType(v)
	return _u
}

// SetNillableTransactionType sets the "transaction_type" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableTransactionType(v *uint8) *TransactionUpdateOne {
	if v != nil {
		_u.SetTransactionType(*v)
	}
	return _u
}

// AddTransactionType adds value to the "transaction_type" field.
func (_u *TransactionUpdateOne) AddTransactionType(v int8) *TransactionUpdateOne {
	_u.mutation.AddTransactionType(v)
	return _u
}

// SetReferenceID sets the "reference_id" field.
func (_u *TransactionUpdateOne) SetReferenceID(v string) *TransactionUpdateOne {
	_u.mutation.SetReferenceID(v)
	return _u
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableReferenceID(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetReferenceID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TransactionUpdateOne) SetStatus(v uint8) *TransactionUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableStatus(v *uint8) *TransactionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TransactionUpdateOne) AddStatus(v int8) *TransactionUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdateOne) SetDescription(v string) *TransactionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableDescription(v *string) *TransactionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (_u *TransactionUpdateOne) SetWallet(v *Wallet) *TransactionUpdateOne {
	return _u.SetWalletID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdateOne) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (_u *TransactionUpdateOne) ClearWallet() *TransactionUpdateOne {
	_u.mutation.ClearWallet()
	return _u
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Transaction entity.
func (_u *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if transaction.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized transaction.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdateOne) check() error {
	if _u.mutation.WalletCleared() && len(_u.mutation.WalletIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Transaction.wallet"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TransactionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransactionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(transaction.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(transaction.FieldUpdatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(transaction.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(transaction.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(transaction.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TransactionType(); ok {
		_spec.SetField(transaction.FieldTransactionType, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedTransactionType(); ok {
		_spec.AddField(transaction.FieldTransactionType, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.ReferenceID(); ok {
		_spec.SetField(transaction.FieldReferenceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(transaction.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(transaction.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.WalletTable,
			Columns: []string{transaction.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Transaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
