// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DriverProfile is the predicate function for driverprofile builders.
type DriverProfile func(*sql.Selector)

// ShipperProfile is the predicate function for shipperprofile builders.
type ShipperProfile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
